// DO NOT EDIT MANUALLY
// This file was automatically generated by `processing/steps/generateTypes.ts`
// To update, run `docker compose up processing`

export type TableId =
  | 'barrierAreas'
  | 'barrierLines'
  | 'bicycleParking_areas'
  | 'bicycleParking_points'
  | 'bikeSuitability'
  | 'bikelanes'
  | 'bikelanesPresence'
  | 'bikeroutes'
  | 'boundaries'
  | 'boundaryLabels'
  | 'landuse'
  | 'places'
  | 'poiClassification'
  | 'publicTransport'
  | 'roads'
  | 'roadsPathClasses'
  | 'todos_lines'
  | 'trafficSigns'
