// Autogenerated by `scripts/MapboxStyles/process.ts`
// Do not change this file manually

export type MapboxStylesByLayerGroupIds =
  | 'atlas_lit'
  | 'atlas_lit_complete'
  | 'atlas_lit_complete_fresh_verified'
  | 'atlas_lit_fresh'
  | 'atlas_lit_verified'
  | 'atlas_places'

export type MapboxStyleLayerGroupLitIds =
  | 'atlas_lit'
  | 'atlas_lit_complete'
  | 'atlas_lit_complete_fresh_verified'
  | 'atlas_lit_fresh'
  | 'atlas_lit_verified'

export type MapboxStyleLayerGroupPlacesIds = 'atlas_places'
