// Autogenerated by `scripts/MapboxStyles/process.ts`
// Do not change this file manually

export type MapboxStylesByLayerGroupIds =
  | 'atlas_bikelanes'
  | 'atlas_bikelanes_complete'
  | 'atlas_bikelanes_fresh_disabled'
  | 'atlas_bikelanes_verified'
  | 'atlas_bikelanespresence_complete'
  | 'atlas_boundaries'
  | 'atlas_education'
  | 'atlas_landuse'
  | 'atlas_lit'
  | 'atlas_lit_complete'
  | 'atlas_lit_fresh'
  | 'atlas_lit_verified'
  | 'atlas_places'
  | 'atlas_placescircle'
  | 'atlas_poiclassification'
  | 'atlas_roadclass_bikeinfra'
  | 'atlas_roadclass_maxspeed'
  | 'atlas_roadclass_oneway'
  | 'atlas_roadclass_roadclass'
  | 'atlas_roadclass_surface'
  | 'atlas_roadclassification'
  | 'atlas_roadclassification_detailed'
  | 'parking_bufferdriveways'
  | 'parking_bufferkerbintersections'
  | 'parking_calculator'
  | 'parking_debug_bus_tram'
  | 'parking_debug_crossings'
  | 'parking_debug_driveways'
  | 'parking_debug_kerb'
  | 'parking_debug_parking_points'
  | 'parking_debug_parking_poly'
  | 'parking_debug_ramps'
  | 'parking_obstacles'
  | 'parking_operator_border_below_other_layer'
  | 'parking_parkinglines'
  | 'parking_parkinglines_completeness'
  | 'parking_parkinglines_surface'
  | 'parking_stats'
  | 'parking_stats_length'

export type MapboxStyleLayerGroupBikelanesIds =
  | 'atlas_bikelanes'
  | 'atlas_bikelanes_complete'
  | 'atlas_bikelanes_fresh_disabled'
  | 'atlas_bikelanes_verified'
  | 'atlas_bikelanespresence_complete'

export type MapboxStyleLayerGroupBikelanespresenceIds = 'atlas_bikelanespresence_complete'

export type MapboxStyleLayerGroupBoundariesIds = 'atlas_boundaries'

export type MapboxStyleLayerGroupEducationIds = 'atlas_education'

export type MapboxStyleLayerGroupLanduseIds = 'atlas_landuse'

export type MapboxStyleLayerGroupLitIds =
  | 'atlas_lit'
  | 'atlas_lit_complete'
  | 'atlas_lit_fresh'
  | 'atlas_lit_verified'

export type MapboxStyleLayerGroupPlacesIds = 'atlas_places' | 'atlas_placescircle'

export type MapboxStyleLayerGroupPlacescircleIds = 'atlas_placescircle'

export type MapboxStyleLayerGroupPoiclassificationIds = 'atlas_poiclassification'

export type MapboxStyleLayerGroupRoadclassIds =
  | 'atlas_roadclass_bikeinfra'
  | 'atlas_roadclass_maxspeed'
  | 'atlas_roadclass_oneway'
  | 'atlas_roadclass_roadclass'
  | 'atlas_roadclass_surface'
  | 'atlas_roadclassification'
  | 'atlas_roadclassification_detailed'

export type MapboxStyleLayerGroupRoadclassificationIds =
  | 'atlas_roadclassification'
  | 'atlas_roadclassification_detailed'

export type MapboxStyleLayerGroupBufferdrivewaysIds = 'parking_bufferdriveways'

export type MapboxStyleLayerGroupBufferkerbintersectionsIds = 'parking_bufferkerbintersections'

export type MapboxStyleLayerGroupCalculatorIds = 'parking_calculator'

export type MapboxStyleLayerGroupDebugIds =
  | 'parking_debug_bus_tram'
  | 'parking_debug_crossings'
  | 'parking_debug_driveways'
  | 'parking_debug_kerb'
  | 'parking_debug_parking_points'
  | 'parking_debug_parking_poly'
  | 'parking_debug_ramps'

export type MapboxStyleLayerGroupObstaclesIds = 'parking_obstacles'

export type MapboxStyleLayerGroupOperatorIds = 'parking_operator_border_below_other_layer'

export type MapboxStyleLayerGroupParkinglinesIds =
  | 'parking_parkinglines'
  | 'parking_parkinglines_completeness'
  | 'parking_parkinglines_surface'

export type MapboxStyleLayerGroupStatsIds = 'parking_stats' | 'parking_stats_length'
