# this file is copied to the staging or production server to be used there

services:
  app:
    image: public.ecr.aws/n0p8j4k5/atlas/blitz:${GITHUB_SHA}
    container_name: blitz
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_DATABASE}?schema=prisma
      SESSIONS_SECRET_KEY:
      NEXT_PUBLIC_APP_ORIGIN:
      NEXT_PUBLIC_APP_ENV:
      NEXT_PUBLIC_OSM_API_URL:
      TRAEFIK_HOST:
      SESSION_SECRET_KEY:
      OSM_CLIENT_ID:
      OSM_CLIENT_SECRET:
      ATLAS_API_KEY:
      S3_KEY:
      S3_SECRET:
      S3_REGION:
    ports:
      - '4000:4000'
    labels:
      traefik.enable: true
      traefik.http.services.container.loadbalancer.server.port: 4000
      traefik.http.routers.container.rule: Host(`${TRAEFIK_HOST}`) || Host(`www.${TRAEFIK_HOST}`)
      traefik.http.routers.container.entrypoints: websecure
      traefik.http.routers.container.tls.certresolver: letsencrypt
      traefik.http.routers.container.tls: true
    networks:
      - processing_app_bridge

networks:
  processing_app_bridge:
    external: true
