services:
  processing:
    image: processing:latest
    build:
      context: .
      dockerfile: ./processing.Dockerfile
    # INFO: Mounting processing as volumen allows us to edit data without constant rebuild
    # However, that would also overwrite the `node_modules` that where build inside docker
    # with local data. The second line prevents this overwrite by excepting the `node_modules`
    # from the mounting.
    volumes:
      - ./processing:/processing
      - /processing/node_modules
    # INFO: The overwrite of `journald` is needed for mac systems which did not work with `journald`
    logging:
      driver: json-file
  app:
    image: app:latest
    build:
      context: .
      dockerfile: ./app.Dockerfile
      target: base
      args:
        NEXT_PUBLIC_APP_ORIGIN: localhost
        NEXT_PUBLIC_APP_ENV: ${NEXT_PUBLIC_APP_ENV}
        NEXT_PUBLIC_OSM_API_URL: ${NEXT_PUBLIC_OSM_API_URL}
    environment:
      NEXT_PUBLIC_APP_ORIGIN: localhost
    logging:
      driver: json-file
    profiles:
      - frontend
  tiles:
    logging:
      driver: json-file
  db:
    # Flags to increase debug levels
    # command: ["-c", "config_file=/postgresql/postgresql.conf", "-c", "log_statement=all", "-c", "log_min_duration_statement=100"]
    logging:
      driver: json-file

configs:
  postgres_conf:
    file: ./configs/postgres.development.conf
