# this file is copied to the staging or production server to be used there

version: '3'
services:
  app:
    command: 'npm run dev'
    image: !reset null
    labels: !reset []
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./src:/app/src
      - ./.next:/app/.next
  tiles:
    labels: !reset []
