services:
  processing:
    image: !reset null
    build:
      context: .
      dockerfile: ./processing.Dockerfile
    volumes:
      - ./processing:/processing
    logging:
      driver: json-file
  app:
    image: !reset null
    build:
      context: .
      dockerfile: ./app.Dockerfile
      target: base
      args:
        NEXT_PUBLIC_APP_ORIGIN: localhost
        NEXT_PUBLIC_APP_ENV: ${NEXT_PUBLIC_APP_ENV}
        NEXT_PUBLIC_OSM_API_URL: ${NEXT_PUBLIC_OSM_API_URL}
    environment:
      NEXT_PUBLIC_APP_ORIGIN: localhost
    logging:
      driver: json-file
    profiles:
      - frontend
configs:
  postgres_conf:
    file: ./configs/postgres.development.conf
