# this file is copied to the staging or production server to be used there

services:
  app:
    image: !reset null
    build:
      context: .
      dockerfile: ./app.Dockerfile
      target: base
    networks: !reset []
    network_mode: 'host'
    volumes:
      - ./src:/app/src
      - ./scripts:/app/scripts
      - ./.next:/app/.next
