# this file is copied to the staging or production server to be used there

version: '3'
services:
  app:
    image: !reset null
    build:
      context: .
      dockerfile: ./app.Dockerfile
      target: base
    entrypoint: npm run
    command: dev
    networks: !reset []
    network_mode: 'host'
    volumes:
      - ./src:/app/src
      - ./.next:/app/.next
