// Autogenerated by `scripts/MapboxStyles/process.ts`
// Do not change this file manually

// This type is used in `mapboxStyleLayers` and gives some visibility into what kind of data we fetch from Mapbox.
export type MapboxStyleLayer = {
  filter?: any
  id: any
  layout?: any
  maxzoom?: any
  minzoom?: any
  paint?: any
  type?: any
}
