describe("a test", function()
  describe("nested test1", function()
    it("test1", function()
      assert.are.same({["a"]= 1}, {a=1})
    end)
    it("test2", function()
      assert.truthy("asd")
    end)
  end)
  describe("nested test2", function()
    it("test3", function()
      assert.falsy(nil)
    end)
    it("test4", function()
      assert.is_true(1 == 1)
    end)
  end)
  describe("nested test3 ", function()
    it("failing test", function()
      assert.is_true(1 == 2)
    end)
  end)
end)
