// Autogenerated by `scripts/MapboxStyles/process.ts`
// Do not change this file manually

import { MapboxStyleLayer } from '../types'

export const mapboxStyleGroupLayers_atlas_bikelanes_plus_widths: MapboxStyleLayer[] = [
  {
    minzoom: 12,
    layout: {
      'symbol-placement': 'line-center',
      'text-size': ['interpolate', ['linear'], ['zoom'], 12, 8, 22, 18],
      'text-font': ['Open Sans SemiBold', 'Arial Unicode MS Regular'],
      'text-padding': 4,
      'text-field': ['to-string', ['get', 'width']],
    },
    type: 'symbol',
    id: 'widths',
    paint: {
      'text-color': ['interpolate', ['linear'], ['zoom'], 12, '#8c8c8c', 16, '#747272'],
    },
  },
]
