// DO NOT EDIT MANUALLY
// This file was automatically generated by `scripts/MapboxStyles/process.ts`

import { MapboxStyleLayer } from '../types'

export const mapboxStyleGroupLayers_atlas_bikelanes_plus_verification: MapboxStyleLayer[] = [
  {
    minzoom: 7,
    filter: ['has', 'category'],
    type: 'line',
    id: 'bikelanes-verification-status',
    paint: {
      'line-width': ['interpolate', ['linear'], ['zoom'], 9, 5, 13, 8, 18, 20],
      'line-color': [
        'case',
        ['==', ['get', 'verified'], 'approved'],
        'hsl(107, 88%, 57%)',
        ['==', ['get', 'verified'], 'rejected'],
        'hsl(0, 100%, 41%)',
        '#fa7fe2',
      ],
      'line-opacity': ['interpolate', ['linear'], ['zoom'], 11.6, 0, 11.8, 1, 12.2, 1, 18, 1],
    },
  },
]
