// DO NOT EDIT MANUALLY
// This file was automatically generated by `scripts/MapboxStyles/process.ts`

import { MapboxStyleLayer } from '../types'

export const mapboxStyleGroupLayers_atlas_bikelanes_plus_bikesuitability: MapboxStyleLayer[] = [
  {
    layout: {
      'line-join': 'round',
      'line-cap': 'round',
    },
    filter: ['has', 'bikeSuitability'],
    type: 'line',
    id: 'bikeSuitability',
    paint: {
      'line-color': [
        'match',
        ['get', 'bikeSuitability'],
        ['goodSurface'],
        '#0fcc51',
        ['noMotorizedVehicle'],
        '#0b7f83',
        ['noOvertaking'],
        '#07dfd7',
        ['livingStreet'],
        '#0bbce0',
        'rgba(240, 0, 0, 0)',
      ],
      'line-opacity': 0.3,
      'line-dasharray': [0.1, 1.5],
      'line-width': ['interpolate', ['linear'], ['zoom'], 9, 1, 11, 3, 12, 5, 16, 10],
    },
  },
]
