// Autogenerated by `scripts/MapboxStyles/process.ts`
// Do not change this file manually

import { MapboxStyleLayer } from '../types'

export const mapboxStyleGroupLayers_atlas_lit_fresh: MapboxStyleLayer[] = [
  {
    layout: {
      'line-cap': 'round',
    },
    type: 'line',
    id: 'lit-fresh-line-checkdate',
    paint: {
      'line-width': ['interpolate', ['linear'], ['zoom'], 12, 3, 18, 4],
      'line-color': [
        'interpolate',
        ['linear'],
        ['get', 'smoothness_age'],
        350,
        '#5bf231',
        351,
        '#dbf231',
        486,
        '#dbf231',
      ],
      'line-opacity': ['interpolate', ['linear'], ['zoom'], 13, 0.8, 18, 0.6],
      'line-blur': 1,
      'line-offset': ['interpolate', ['linear'], ['zoom'], 12, 1.5, 18, 5],
    },
    filter: ['has', 'lit_age'],
  },
  {
    layout: {
      'line-cap': 'round',
    },
    filter: ['!', ['has', 'lit_age']],
    type: 'line',
    id: 'lit-fresh-line-updatedat',
    paint: {
      'line-width': ['interpolate', ['linear'], ['zoom'], 12, 3, 18, 4],
      'line-color': [
        'interpolate',
        ['linear'],
        ['get', 'updated_age'],
        350,
        '#d10000',
        351,
        '#7e0101',
        486,
        '#7e0101',
      ],
      'line-opacity': ['interpolate', ['linear'], ['zoom'], 13, 0.8, 18, 0.6],
      'line-blur': 1,
      'line-offset': ['interpolate', ['linear'], ['zoom'], 12, 1.5, 18, 5],
    },
  },
]
