// DO NOT EDIT MANUALLY
// This file was automatically generated by `scripts/MapboxStyles/process.ts`

import { MapboxStyleLayer } from '../types'

export const mapboxStyleGroupLayers_atlas_bikelanes_widths: MapboxStyleLayer[] = [
  {
    id: 'widths-lines-incomplete',
    type: 'line',
    paint: {
      'line-offset': ['interpolate', ['linear'], ['zoom'], 12, 0, 15, -1],
      'line-color': '#fda5e4',
      'line-width': ['interpolate', ['linear'], ['zoom'], 12, 1, 22, 4],
      'line-dasharray': [3, 1],
    },
    filter: ['!', ['has', 'width']],
  },
  {
    id: 'widths-lines',
    type: 'line',
    paint: {
      'line-width': ['interpolate', ['linear'], ['zoom'], 10, 1.5, 14, 3, 16, 4],
      'line-offset': ['interpolate', ['linear'], ['zoom'], 12, 0, 15, -1],
      'line-color': [
        'interpolate',
        ['linear'],
        ['get', 'width'],
        0.5,
        '#ef9043',
        1.1,
        '#f6de09',
        1.6,
        '#a1e217',
        2.2,
        '#15c65c',
      ],
    },
    filter: ['has', 'width'],
  },
]
