// DO NOT EDIT MANUALLY
// This file was automatically generated by `scripts/MapboxStyles/process.ts`

import { MapboxStyleLayer } from '../types'

export const mapboxStyleGroupLayers_atlas_mask_boundary: MapboxStyleLayer[] = [
  {
    minzoom: 2,
    type: 'line',
    id: 'region-boundary',
    paint: {
      'line-dasharray': ['step', ['zoom'], ['literal', [2, 0]], 7, ['literal', [2, 2, 6, 2]]],
      'line-width': ['interpolate', ['linear'], ['zoom'], 3, 0.7, 12, 1.5],
      'line-opacity': ['interpolate', ['linear'], ['zoom'], 2, 0, 3, 1, 9, 1, 10, 0.1],
      'line-color': '#dfa762',
    },
  },
  {
    minzoom: 7,
    type: 'line',
    id: 'region-boundary-bg',
    paint: {
      'line-color': 'hsl(45, 2%, 80%)',
      'line-width': ['interpolate', ['linear'], ['zoom'], 3, 3, 12, 6],
      'line-opacity': ['interpolate', ['linear'], ['zoom'], 7, 0, 8, 0.5, 9, 0.5, 10, 0.1],
      'line-dasharray': [1, 0],
      'line-blur': ['interpolate', ['linear'], ['zoom'], 3, 0, 12, 3],
    },
  },
]
