// Autogenerated by `scripts/MapboxStyles/process.ts`
// Do not change this file manually

import { MapboxStyleLayer } from '../types'

export const mapboxStyleGroupLayers_parking_debug_ramps: MapboxStyleLayer[] = [
  {
    type: 'fill',
    id: 'parking-ramps-area',
    paint: {
      'fill-color': 'rgba(148, 163, 184, 0.7)',
    },
    minzoom: 15,
  },
  {
    minzoom: 16.5,
    type: 'line',
    id: 'parking-ramps-border',
    paint: {
      'line-dasharray': [2, 2],
      'line-color': 'rgb(0, 0, 0)',
    },
  },
]
