// Autogenerated by `scripts/MapboxStyles/process.ts`
// Do not change this file manually

import { MapboxStyleLayer } from '../types'

export const mapboxStyleGroupLayers_parking_parkinglines_missing: MapboxStyleLayer[] = [
  {
    id: 'not expected',
    type: 'line',
    paint: {
      'line-color': 'rgb(187, 17, 133)',
      'line-width': ['interpolate', ['linear'], ['zoom'], 16, 2, 20, 10],
      'line-opacity': [
        'match',
        ['get', 'highway'],
        ['secondary', 'construction', 'pedestrian'],
        0.25,
        1,
      ],
    },
    filter: ['match', ['get', 'capacity_status'], ['data_missing'], true, false],
  },
]
