// DO NOT EDIT MANUALLY
// This file was automatically generated by `scripts/MapboxStyles/process.ts`

import { MapboxStyleLayer } from '../types'

export const mapboxStyleGroupLayers_parking_stats: MapboxStyleLayer[] = [
  {
    filter: ['has', 'admin_level'],
    type: 'fill',
    id: 'area-0-to-100',
    paint: {
      'fill-color': [
        'interpolate',
        ['linear'],
        ['to-number', ['get', 'done_percent']],
        0,
        'rgb(195, 179, 255)',
        80,
        'rgb(122, 0, 163)',
      ],
      'fill-outline-color': 'hsl(0, 100%, 100%)',
      'fill-opacity': 0.35,
    },
  },
  {
    type: 'line',
    id: 'line',
    paint: {
      'line-color': 'hsl(0, 0%, 100%)',
      'line-opacity': 0.63,
    },
  },
  {
    layout: {
      'text-field': ['to-string', ['get', 'done_percent']],
    },
    type: 'symbol',
    id: 'label',
    paint: {
      'text-color': 'rgba(69, 0, 112, 0.95)',
      'text-halo-width': 1,
      'text-halo-color': 'hsl(291, 0%, 100%)',
      'text-halo-blur': 1,
    },
  },
]
