// DO NOT EDIT MANUALLY
// This file was automatically generated by `scripts/MapboxStyles/process.ts`

import { MapboxStyleLayer } from '../types'

export const mapboxStyleGroupLayers_radinfra_campaign: MapboxStyleLayer[] = [
  {
    layout: {
      'line-join': 'round',
      'line-cap': 'round',
    },
    type: 'line',
    id: 'campaign-line',
    paint: {
      'line-color': '#fda5e4',
      'line-opacity': [
        'interpolate',
        ['linear'],
        ['zoom'],
        0,
        0.6,
        12,
        0.6,
        14,
        0.9,
        16,
        0.9,
        22,
        0.2,
      ],
      'line-width': ['interpolate', ['linear'], ['zoom'], 0, 7, 6, 7, 16, 4, 18, 14, 22, 16],
    },
  },
]
