// DO NOT EDIT MANUALLY
// This file was automatically generated by `scripts/MapboxStyles/process.ts`

import { MapboxStyleLayer } from '../types'

export const mapboxStyleGroupLayers_radinfra_width: MapboxStyleLayer[] = [
  {
    type: 'line',
    id: 'width-missing',
    paint: {
      'line-width': ['interpolate', ['linear'], ['zoom'], 12, 1, 22, 4],
      'line-offset': ['interpolate', ['linear'], ['zoom'], 12, 0, 15, -1],
      'line-color': '#fda5e4',
      'line-dasharray': [3, 1],
    },
    filter: ['any', ['!', ['has', 'width']], ['match', ['get', 'width'], [''], true, false]],
    layout: {
      'line-cap': 'round',
      'line-join': 'round',
    },
  },
  {
    type: 'line',
    id: 'hitarea-missing-width',
    paint: {
      'line-offset': ['interpolate', ['linear'], ['zoom'], 12, 0, 15, -1],
      'line-width': ['interpolate', ['linear'], ['zoom'], 9, 1, 14.1, 10, 22, 12],
      'line-color': 'rgb(216, 20, 255)',
      'line-dasharray': [3, 1],
      'line-opacity': 0,
    },
    layout: {
      'line-join': 'round',
      'line-cap': 'round',
    },
    filter: ['any', ['!', ['has', 'width']], ['match', ['get', 'width'], [''], true, false]],
  },
  {
    type: 'line',
    id: 'width-colors',
    paint: {
      'line-width': ['interpolate', ['linear'], ['zoom'], 10, 1.5, 16, 4],
      'line-offset': ['interpolate', ['linear'], ['zoom'], 12, 0, 15, -1],
      'line-color': [
        'interpolate',
        ['linear'],
        ['get', 'width'],
        0.5,
        '#ef9043',
        1.1,
        '#f6de09',
        1.6,
        '#a1e217',
        2.2,
        '#15c65c',
      ],
    },
    filter: ['has', 'width'],
  },
]
