// Autogenerated by `scripts/MapboxStyles/process.ts`
// Do not change this file manually

import { MapboxStyleLayer } from '../types'

export const mapboxStyleGroupLayers_radinfra_currentness: MapboxStyleLayer[] = [
  {
    type: 'line',
    id: 'current-colors',
    paint: {
      'line-offset': ['interpolate', ['linear'], ['zoom'], 12, 0, 15, -1],
      'line-width': ['interpolate', ['linear'], ['zoom'], 10, 1.5, 14, 3, 16, 4],
      'line-color': ['step', ['get', 'updated_age'], '#15c65c', 1095, '#f6de09', 2190, '#fda5e4'],
    },
    layout: {
      'line-join': 'round',
      'line-cap': 'round',
    },
  },
]
