// DO NOT EDIT MANUALLY
// This file was automatically generated by `scripts/MapboxStyles/process.ts`

import { MapboxStyleLayer } from '../types'

export const mapboxStyleGroupLayers_radinfra_smoothness: MapboxStyleLayer[] = [
  {
    layout: {
      'line-join': 'round',
      'line-cap': 'round',
    },
    type: 'line',
    id: 'smooth-missing',
    paint: {
      'line-offset': ['interpolate', ['linear'], ['zoom'], 12, 0, 15, -1],
      'line-color': '#fda5e4',
      'line-width': ['interpolate', ['linear'], ['zoom'], 12, 1, 22, 4],
      'line-dasharray': [3, 1],
    },
    filter: [
      'any',
      ['!', ['has', 'smoothness']],
      ['match', ['get', 'smoothness'], [''], true, false],
    ],
  },
  {
    layout: {
      'line-cap': 'round',
      'line-join': 'round',
    },
    type: 'line',
    id: 'smooth-colors',
    paint: {
      'line-offset': ['interpolate', ['linear'], ['zoom'], 12, 0, 15, -1],
      'line-color': [
        'match',
        ['get', 'smoothness'],
        ['very_bad'],
        '#d8035c',
        ['bad'],
        '#f90606',
        ['intermediate'],
        '#faa00f',
        ['good'],
        '#b5ea2e',
        ['excellent'],
        '#37f644',
        'rgba(0, 0, 0, 0)',
      ],
      'line-width': ['interpolate', ['linear'], ['zoom'], 10, 1.5, 16, 4],
    },
    filter: ['has', 'smoothness'],
  },
]
