// Autogenerated by `scripts/MapboxStyles/process.ts`
// Do not change this file manually

import { MapboxStyleLayer } from '../types'

export const mapboxStyleGroupLayers_radinfra_campaign: MapboxStyleLayer[] = [
  {
    layout: {
      'line-join': 'round',
      'line-cap': 'round',
    },
    type: 'line',
    id: 'campaign-fake-heatmap',
    paint: {
      'line-color': '#a97bea',
      'line-width': ['interpolate', ['linear'], ['zoom'], 0, 8, 10, 7, 14, 6, 18, 0],
    },
  },
  {
    minzoom: 11,
    type: 'line',
    id: 'campaign-line',
    paint: {
      'line-color': '#a97bea',
      'line-opacity': 0.6,
      'line-width': 4,
    },
    layout: {
      'line-join': 'round',
      'line-cap': 'round',
    },
  },
]
