// DO NOT EDIT MANUALLY
// This file was automatically generated by `scripts/MapboxStyles/process.ts`

import { MapboxStyleLayer } from '../types'

export const mapboxStyleGroupLayers_radinfra_currentness: MapboxStyleLayer[] = [
  {
    type: 'line',
    id: 'current-colors',
    paint: {
      'line-offset': ['interpolate', ['linear'], ['zoom'], 12, 0, 15, -1],
      'line-width': ['interpolate', ['linear'], ['zoom'], 10, 1.5, 14, 3, 16, 4],
      'line-color': ['step', ['get', 'updated_age'], '#15c65c', 2370, '#f6de09', 3650, '#fda5e4'],
    },
    layout: {
      'line-join': 'round',
      'line-cap': 'round',
    },
    filter: ['has', 'updated_age'],
  },
  {
    type: 'line',
    id: 'current-zoomed-out',
    paint: {
      'line-offset': ['interpolate', ['linear'], ['zoom'], 12, 0, 15, -1],
      'line-width': ['interpolate', ['linear'], ['zoom'], 10, 1.5, 14, 3, 16, 4],
      'line-color': 'gray',
    },
    layout: {
      'line-join': 'round',
      'line-cap': 'round',
    },
    filter: ['!', ['has', 'updated_age']],
  },
]
