// DO NOT EDIT MANUALLY
// This file was automatically generated by `scripts/MapboxStyles/process.ts`

import { MapboxStyleLayer } from '../types'

export const mapboxStyleGroupLayers_radinfra_traffic_signs: MapboxStyleLayer[] = [
  {
    minzoom: 8,
    layout: {
      'line-cap': 'round',
      'line-join': 'round',
    },
    filter: ['!', ['has', 'traffic_sign']],
    type: 'line',
    id: 'sign-missing',
    paint: {
      'line-color': '#fda5e4',
      'line-width': ['interpolate', ['linear'], ['zoom'], 10, 1.5, 20, 4],
      'line-opacity': 0.6,
      'line-offset': ['interpolate', ['linear'], ['zoom'], 12, 0, 15, -1],
      'line-dasharray': [3, 1],
    },
  },
  {
    minzoom: 8,
    layout: {
      'line-cap': 'round',
      'line-join': 'round',
    },
    filter: ['has', 'traffic_sign'],
    type: 'line',
    id: 'sign-colors',
    paint: {
      'line-color': ['match', ['get', 'traffic_sign'], ['none'], '#00c29e', '#a1e217'],
      'line-width': ['interpolate', ['linear'], ['zoom'], 10, 1.5, 16, 4],
      'line-opacity': 0.6,
    },
  },
  {
    layout: {
      'line-join': 'round',
      'line-cap': 'round',
    },
    maxzoom: 9,
    filter: ['!', ['has', 'traffic_sign']],
    type: 'line',
    id: 'current-zoomed-out-traffic-signs',
    paint: {
      'line-offset': ['interpolate', ['linear'], ['zoom'], 12, 0, 15, -1],
      'line-width': ['interpolate', ['linear'], ['zoom'], 10, 1.5, 16, 4],
      'line-color': 'gray',
    },
  },
]
