// Autogenerated by `scripts/MapboxStyles/process.ts`
// Do not change this file manually

import { MapboxStyleLayer } from '../types'

export const mapboxStyleGroupLayers_radinfra_plus_missing: MapboxStyleLayer[] = [
  {
    minzoom: 11,
    layout: {
      'line-cap': 'round',
      'line-join': 'round',
    },
    filter: ['!', ['has', 'traffic_sign']],
    type: 'line',
    id: 'plus_highlight_missing',
    paint: {
      'line-color': '#a97bea',
      'line-width': 10,
      'line-opacity': 0.6,
    },
  },
]
