-- Auto-generated using processing/utils/initializeLuaPackagePath.ts
-- Runs on every processing run.
-- Extends the package.path to include all folders that have a .lua file (except for '__test__' folders).
-- We import this file via `require('init')` in every lua file.
package.path = package.path .. ";/processing/?.lua"
package.path = package.path .. ";/processing/topics/barriers/?.lua"
package.path = package.path .. ";/processing/topics/bicycleParking/?.lua"
package.path = package.path .. ";/processing/topics/bikeroutes/?.lua"
package.path = package.path .. ";/processing/topics/boundaries/?.lua"
package.path = package.path .. ";/processing/topics/helper/?.lua"
package.path = package.path .. ";/processing/topics/landuse/?.lua"
package.path = package.path .. ";/processing/topics/parking/?.lua"
package.path = package.path .. ";/processing/topics/parking/errors/?.lua"
package.path = package.path .. ";/processing/topics/parking/helper/?.lua"
package.path = package.path .. ";/processing/topics/parking/obstacles/?.lua"
package.path = package.path .. ";/processing/topics/parking/obstacles/area/?.lua"
package.path = package.path .. ";/processing/topics/parking/obstacles/helper/?.lua"
package.path = package.path .. ";/processing/topics/parking/obstacles/line/?.lua"
package.path = package.path .. ";/processing/topics/parking/obstacles/point/?.lua"
package.path = package.path .. ";/processing/topics/parking/off_street_parking/?.lua"
package.path = package.path .. ";/processing/topics/parking/off_street_parking/areas/?.lua"
package.path = package.path .. ";/processing/topics/parking/off_street_parking/helper/?.lua"
package.path = package.path .. ";/processing/topics/parking/off_street_parking/points/?.lua"
package.path = package.path .. ";/processing/topics/parking/parkings/?.lua"
package.path = package.path .. ";/processing/topics/parking/parkings/helper/?.lua"
package.path = package.path .. ";/processing/topics/parking/roads/?.lua"
package.path = package.path .. ";/processing/topics/parking/roads/helper/?.lua"
package.path = package.path .. ";/processing/topics/places/?.lua"
package.path = package.path .. ";/processing/topics/poiClassification/?.lua"
package.path = package.path .. ";/processing/topics/publicTransport/?.lua"
package.path = package.path .. ";/processing/topics/roads_bikelanes/?.lua"
package.path = package.path .. ";/processing/topics/roads_bikelanes/bikelanes/?.lua"
package.path = package.path .. ";/processing/topics/roads_bikelanes/bikelanes/categories/?.lua"
package.path = package.path .. ";/processing/topics/roads_bikelanes/lit/?.lua"
package.path = package.path .. ";/processing/topics/roads_bikelanes/maxspeed/?.lua"
package.path = package.path .. ";/processing/topics/roads_bikelanes/paths/?.lua"
package.path = package.path .. ";/processing/topics/roads_bikelanes/roads/?.lua"
package.path = package.path .. ";/processing/topics/roads_bikelanes/surfaceQuality/?.lua"
package.path = package.path .. ";/processing/topics/trafficSigns/?.lua"
package.path = package.path .. ";/processing/utils/?.lua"
package.path = package.path .. ";/processing/utils/types/?.lua"

-- print('Known package path from `init.lua`: ' .. package.path) -- Use for temp debugging only because it breaks our `writeTodoIdTypes` helper because this print is added to that resuls "array".
