// DO NOT EDIT MANUALLY
// this file was automatically generated by `saveConfigs.ts`

import { _1cjo3ur } from './_1cjo3ur'
import { _1d3t4i0 } from './_1d3t4i0'
import { _1dhu3si } from './_1dhu3si'
import { _1j7ax4m } from './_1j7ax4m'
import { _1oy2q4i } from './_1oy2q4i'
import { _1p0kkkw } from './_1p0kkkw'
import { _1x5utcr } from './_1x5utcr'
import { _c8lcr0 } from './_c8lcr0'
import { _eu560i } from './_eu560i'
import { _nq3m12 } from './_nq3m12'
import { _tztqka } from './_tztqka'
import { _wvqr4 } from './_wvqr4'

export const configs = {
  '1cjo3ur': _1cjo3ur,
  '1d3t4i0': _1d3t4i0,
  '1dhu3si': _1dhu3si,
  '1j7ax4m': _1j7ax4m,
  '1oy2q4i': _1oy2q4i,
  '1p0kkkw': _1p0kkkw,
  '1x5utcr': _1x5utcr,
  c8lcr0: _c8lcr0,
  eu560i: _eu560i,
  nq3m12: _nq3m12,
  tztqka: _tztqka,
  wvqr4: _wvqr4,
}
