name: Check PR
on: [pull_request]
jobs:
  run-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./processing.Dockerfile
          tags: test_img
          target: lua
          push: false
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run Tests
        run: |
          docker run -v ./processing:/processing test_img busted /processing/topics/ -p %.test%.lua$
