name: Regenerate production tiles

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * 1-5"

jobs:
  trigger_generation:
    environment:
      name: production
      url: https://tiles.radverkehrsatlas.de
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - name: Restart tarmac production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            echo "Restart tarmac container"
            cd /srv/processing/
            docker compose restart -t 30 app
