name: Restart martin

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * 1-5"

jobs:
  trigger_generation:
    environment:
      name: production
      url: https://tiles.radverkehrsatlas.de
    runs-on: ubuntu-latest

    steps:
      - name: Restart martin server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            echo "Restart martin"
            cd /srv/processing/
            docker compose restart -t 30 tiles
