-- Generated by Copilot
function Inspect(tbl, indent)
  indent = indent or 0
  local toprint = string.rep(" ", indent) .. "{\n"
  indent = indent + 2
  for k, v in pairs(tbl) do
    toprint = toprint .. string.rep(" ", indent)
    if type(k) == "number" then
      toprint = toprint .. "[" .. k .. "] = "
    else
      toprint = toprint .. k .. " = "
    end
    if type(v) == "table" then
      toprint = toprint .. Inspect(v, indent + 2) .. ",\n"
    else
      toprint = toprint .. tostring(v) .. ",\n"
    end
  end
  toprint = toprint .. string.rep(" ", indent - 2) .. "}"
  return toprint
end
