#!/usr/bin/env bun

// This script generates the files `./_{checksum}.ts` and `./index.ts`
// don't run it directly but use `npm run save-configs` which run prettier after code generation

import fs from 'node:fs'
import path from 'node:path'
import { getSimplifiedConfigs } from './lib'

const configsFolder = path.join(import.meta.dir, 'configs')

const resultIntro = `
// DO NOT EDIT MANUALLY
// This file was automatically generated by \`${import.meta.file}\`
`

Object.entries(getSimplifiedConfigs()).forEach(([checksum, { simplifiedConfig, region }]) => {
  const moduleSaveRegionSlug = region.slug.toLocaleLowerCase().replace(/[^a-z0-9]+/g, '')
  const moduleName = `${moduleSaveRegionSlug}_${checksum}`
  const modulePath = path.join(configsFolder, `${moduleSaveRegionSlug}_${checksum}.ts`)
  const result = `${resultIntro}
import { MapDataCategoryParam } from '../../type'

// For region ${region.slug} (${region.name})
export const ${moduleName}: MapDataCategoryParam[] = ${JSON.stringify(simplifiedConfig)}
    `
  Bun.write(modulePath, result)
  console.log(`Updated ${modulePath}...`)
})

const configModules = fs
  .readdirSync(configsFolder)
  .filter((filename) => !filename.startsWith('index'))
  .map((filename) => filename.split('.')[0])
  .sort()

const importCode = configModules
  .map((filename) => {
    return `import { ${filename} } from './${filename}'`
  })
  .join('\n')

const result = `${resultIntro}

${importCode}

export const configs = {
  ${configModules.map((filename) => {
    // The legacy modules are prefixed with "_" but newers are prefix by the (cleaned) `region.slug`
    // For newer configs we need to remove the `region.slug` to allow lookup by checksum.
    const moduleName = filename?.startsWith('_') ? filename!.slice(1) : filename?.split('_').at(1)
    return `"${moduleName}": ${filename}`
  })}
}
`
const modulePath = path.join(configsFolder, 'index.ts')
Bun.write(modulePath, result)
console.log(`Updated ${modulePath}...`)
