import { MapDataVisLayer } from '../../types'
import { layerLabel } from './layerLabel.const'

export const layersDefault = (source: string, sourceLayer: string) => {
  return [
    {
      id: 'line-present',
      type: 'line',
      source: source,
      'source-layer': sourceLayer,
      filter: [
        'all',
        [
          'in',
          'orientation',
          'half_on_kerb',
          'marked',
          'mixed',
          'parallel',
          'perpendicular',
          'street_side',
          'yes',
          'diagonal',
        ],
      ],
      paint: { 'line-width': 4, 'line-color': 'rgba(110, 165, 9, 1)' },
    },
    {
      id: 'hitarea--line-present',
      type: 'line',
      source: source,
      'source-layer': sourceLayer,
      filter: [
        'all',
        [
          'in',
          'orientation',
          'half_on_kerb',
          'marked',
          'mixed',
          'parallel',
          'perpendicular',
          'street_side',
          'yes',
          'diagonal',
        ],
      ],
      paint: { 'line-width': 8, 'line-color': 'rgba(110, 165, 9, 0)' },
    },
    {
      id: 'line-no',
      type: 'line',
      source: source,
      'source-layer': sourceLayer,
      filter: ['all', ['in', 'orientation', 'no', 'no_parking', 'no_stopping']],
      paint: {
        'line-width': 2,
        'line-color': 'rgba(233, 171, 148, 1)',
      },
    },
    {
      id: 'line-not-present',
      type: 'line',
      source: source,
      'source-layer': sourceLayer,
      filter: [
        'all',
        [
          '!in',
          'orientation',
          'no',
          'no_parking',
          'no_stopping',
          'separate',
          'half_on_kerb',
          'marked',
          'mixed',
          'parallel',
          'perpendicular',
          'street_side',
          'yes',
          'diagonal',
        ],
      ],
      paint: {
        'line-width': 3,
        'line-color': 'rgba(153, 164, 241, 1)',
      },
    },
    {
      id: 'hitarea--line-not-present',
      type: 'line',
      source: source,
      'source-layer': sourceLayer,
      filter: [
        'all',
        [
          '!in',
          'orientation',
          'no',
          'no_parking',
          'no_stopping',
          'separate',
          'half_on_kerb',
          'marked',
          'mixed',
          'parallel',
          'perpendicular',
          'street_side',
          'yes',
          'diagonal',
        ],
      ],
      paint: {
        'line-width': 6,
        'line-color': 'rgba(153, 164, 241, 0)',
      },
    },
    layerLabel('capacity'),
  ] as MapDataVisLayer[]
}
