// DO NOT EDIT MANUALLY
// This file was automatically generated by `app/scripts/RadinfraDeCampaigns/updateCache.ts`
// To update, restart the dev server or run `npm run predev:update_campaigns`

import { RadinfraDeCampaignSchema } from './radinfraDeCampaignSchema'

export const radinfraDeCampaigns: RadinfraDeCampaignSchema[] = [
  {
    id: 'adjoining_or_isolated',
    name: 'Ergänze ob die Fahrradinfrastruktur straßenbegleitend oder selbstständig geführt ist (Alpha-Version)',
    menuTitle: 'Straßenbegleitend oder selbstständig geführt?',
    pubDate: '2025-01-01T15:00:00.000Z',
    visibility: 'secondary',
    category: 'radinfra',
    description:
      'Diese Kampagne enthält Wege, deren Führungsform [im Radverkehrsatlas](https://radverkehrsatlas.de/) nicht präzise angegeben werden kann. (Aktuell werden nur Wege der Kategorie "Radweg" aufgenommen.)',
    task: '**Bitte prüfe ob die Radinfrastruktur straßenbegleitend ist und ergänze den fehlenden Zugangs-Tag `is_sidepath=yes` oder `no`.** Weitere Hinweise findet Du in der Aufgabenbeschreibung.\n',
    maprouletteChallenge: {
      discriminant: true,
      value: {
        id: 50885,
        enabled: true,
        name: 'Fahrradinfrastruktur straßenbegleitend oder selbstständig geführt?',
        resultsLimited: false,
      },
    },
  },
  {
    id: 'advisory_or_exclusive',
    name: 'Ergänze, ob es sich um einen Schutzstreifen oder Angebotsstreifen handelt (Alpha-Version)',
    menuTitle: 'Schutzstreifen oder Angebotsstreifen?',
    pubDate: '2025-01-01T15:00:00.000Z',
    visibility: 'secondary',
    category: 'radinfra',
    description:
      'Diese Kampagne enthält Radinfrastruktur auf der Fahrbahn bei denen die Angabe fehlt, ob es sich um einen Schutzstreifen oder Angebotsstreifen handelt.',
    task: '**Bitte prüfe die Radinfrastruktur und ergänze die nötigen Attribute.** Weitere Hinweise findet Du in der Aufgabenbeschreibung.',
    maprouletteChallenge: {
      discriminant: true,
      value: {
        id: 50888,
        enabled: true,
        name: 'Schutzstreifen oder Angebotsstreifen?',
        resultsLimited: false,
      },
    },
  },
  {
    id: 'currentness_too_old',
    name: 'Radinfrastruktur die seit langer Zeit nicht editiert wurde',
    menuTitle: 'Sehr lange nicht geprüfte Wege',
    pubDate: '2025-01-01T15:00:00.000Z',
    visibility: 'promote',
    category: 'currentness',
    description: 'Diese Kampagne enthält Wege, die seit mehr als 6 Jahren nicht editiert wurden.',
    task: '**Bitte prüfe und aktualisiere diese Infrastruktur.** Weitere Hinweise findet Du in der Aufgabenbeschreibung.',
    maprouletteChallenge: {
      discriminant: true,
      value: {
        id: 51041,
        enabled: true,
        name: 'Sehr lange nicht geprüfte Wege',
        resultsLimited: false,
      },
    },
  },
  {
    id: 'deprecated_cycleway_shared',
    name: 'Die Angabe `cycleway=shared` soll nicht mehr verwendet werden (Alpha-Version)',
    menuTitle: 'Veraltetes Tagging (`shared`)',
    pubDate: '2025-01-01T15:00:00.000Z',
    visibility: 'secondary',
    category: 'radinfra',
    description:
      'Diese Kampagne enthält Wege, die die veraltete Angabe `cycleway=shared` verwenden.',
    task: '**Bitte ändere das Tagging. In vielen Fällen kann es ersatzlos gestrichen werden. Es ist aber wichtig, die Infrastruktur in diesem Zuge zu prüfen.** Weitere Hinweise findet Du in der Aufgabenbeschreibung.',
    maprouletteChallenge: {
      discriminant: true,
      value: {
        id: 50889,
        enabled: true,
        name: 'Veraltetes Tagging (`cycleway=shared`)',
        resultsLimited: false,
      },
    },
  },
  {
    id: 'missing_access_tag_240',
    name: 'Ergänze das Zugangs-Tagging für Geh-/Radwege (Alpha-Version)',
    menuTitle: 'Zugangs-Tagging fehlt (Geh-/Radweg)',
    pubDate: '2025-01-01T15:00:00.000Z',
    visibility: 'secondary',
    category: 'radinfra',
    description:
      'Diese Kampagne enthält Wege die mit dem Verkehrszeichen `240` (Gem. Geh- und Radweg) oder `241` (Getr. Rad- und Gehweg) markiert sind aber das dazu passende Zugangs-Tagging fehlt.',
    task: '**Bitte prüfe die Radinfrastruktur und ergänze die Zugangs-Tags.** Weitere Hinweise findet Du in der Aufgabenbeschreibung.',
    maprouletteChallenge: {
      discriminant: true,
      value: {
        id: 50890,
        enabled: true,
        name: 'Geh-/Radweg: Zugangs-Tagging fehlt?',
        resultsLimited: false,
      },
    },
  },
  {
    id: 'missing_access_tag_bicycle_road',
    name: 'Fahrradstraßen mit fehlendem `bicycle=designated` (Alpha-Version)',
    menuTitle: 'Zugangs-Tagging fehlt (Fahrradstraße)',
    pubDate: '2024-10-01T15:00:00.000Z',
    visibility: 'secondary',
    category: 'traffic_signs',
    description:
      'Diese Kampagne enthält Wege, die [im Radverkehrsatlas](https://radverkehrsatlas.de/) als Fahrradstraße klassifiziert sind, bei denen jedoch das `bicycle=designated` fehlt.',
    task: '**Bitte prüfe die Situation und ergänze den fehlenden Zugangs-Tag `bicycle=designated`.** Weitere Hinweise findet Du in der Aufgabenbeschreibung.',
    maprouletteChallenge: {
      discriminant: true,
      value: {
        id: 49368,
        enabled: true,
        name: 'Fahrradstraßen mit fehlendem `bicycle=designated`',
        resultsLimited: false,
      },
    },
  },
  {
    id: 'missing_segregated',
    name: 'Ergänze Angaben zur Trennung von Fahrrad- und Fußverkehr auf Geh-/Radwegen (Alpha-Version)',
    menuTitle: 'Gemeinsame oder getrennte Führung?',
    pubDate: '2024-09-20T15:00:00.000Z',
    visibility: 'secondary',
    category: 'radinfra',
    description:
      'Diese Kampagne enthält Wege, die sowohl von Fahrrad- als auch Fußverkehr genutzt werden. Es fehlt aber die Angabe, ob eine Trennung der Verkehrsformen vorliegt.',
    task: '**Bitte ergänze die Angabe `segregated=yes` oder `no`.** Weitere Hinweise findet Du in der Aufgabenbeschreibung.',
    maprouletteChallenge: {
      discriminant: true,
      value: {
        id: 50887,
        enabled: true,
        name: 'Geh-/Radweg: Gemeinsame oder getrennte Führung?',
        resultsLimited: false,
      },
    },
  },
  {
    id: 'missing_surface',
    name: 'Ergänze Angaben Oberfläche',
    menuTitle: 'Wie ist die Oberfläche?',
    pubDate: '2025-01-01T15:00:00.000Z',
    visibility: 'secondary',
    category: 'surface',
    description: 'Diese Kampagne enthält Wege, bei denen die Angabe zur Oberfläche fehlt.',
    task: '**Bitte ergänze die Oberfläche `surface` und gerne auch die Oberflächenqualität `smoothness`.** Weitere Hinweise findet Du in der Aufgabenbeschreibung.',
    maprouletteChallenge: {
      discriminant: false,
    },
  },
  {
    id: 'missing_traffic_sign',
    name: 'Radinfrastruktur ohne Verkehrszeichen',
    menuTitle: 'Fehlendes Verkehrszeichen (Generell)',
    pubDate: '2025-01-01T15:00:00.000Z',
    visibility: 'secondary',
    category: 'traffic_signs',
    description:
      'Diese Kampagne enthält Wege, die [im Radverkehrsatlas](https://radverkehrsatlas.de/) als Radinfrastruktur kategorisiert wurden, jedoch fehlt das zugehörige Verkehrszeichen.',
    task: '**Bitte ergänze fehlende Verkehrszeichen oder ein explizites `traffic_sign=none`.** Weitere Hinweise findet Du in der Aufgabenbeschreibung.',
    maprouletteChallenge: {
      discriminant: false,
    },
  },
  {
    id: 'missing_traffic_sign_244',
    name: 'Fahrradstraßen ohne Verkehrszeichen (Alpha-Version)',
    menuTitle: 'Fehlendes Verkehrszeichen (Fahrradstraße)',
    pubDate: '2024-09-20T15:00:00.000Z',
    visibility: 'promote',
    category: 'traffic_signs',
    description:
      'Diese Kampagne enthält Wege, die [im Radverkehrsatlas](https://radverkehrsatlas.de/) als Fahrradstraße kategorisiert wurden, jedoch fehlt das zugehörige Verkehrszeichen.',
    task: '**Bitte ergänze fehlende Verkehrszeichen oder ein explizites `traffic_sign=none`.** Weitere Hinweise findet Du in der Aufgabenbeschreibung.',
    maprouletteChallenge: {
      discriminant: true,
      value: {
        id: 49357,
        enabled: true,
        name: 'Fahrradstraßen ohne Verkehrszeichen',
        resultsLimited: false,
        rebuildAt: '2025-02-14T09:32:00.000Z',
      },
    },
  },
  {
    id: 'missing_traffic_sign_vehicle_destination',
    name: 'Fahrradstraßen ohne Zusatzzeichen »Anlieger frei« (Alpha-Version)',
    menuTitle: 'Fahrradstraßen ohne Zusatzzeichen',
    pubDate: '2024-10-01T15:00:00.000Z',
    visibility: 'secondary',
    category: 'traffic_signs',
    description:
      "Diese Kampagne enthält Wege, die [im Radverkehrsatlas](https://radverkehrsatlas.de/) als Fahrradstraße mit 'Anlieger frei'-Freigabe für Kfz kategorisiert wurden, jedoch fehlt das zugehörige Zusatzzeichen.",
    task: '**Bitte ergänze fehlende Verkehrszeichen oder ein explizites `traffic_sign=none`.** Weitere Hinweise findet Du in der Aufgabenbeschreibung.',
    maprouletteChallenge: {
      discriminant: true,
      value: {
        id: 49363,
        enabled: true,
        name: 'Fahrradstraßen ohne Zusatzzeichen »Anlieger frei«',
        resultsLimited: false,
      },
    },
  },
  {
    id: 'missing_width',
    name: 'Ergänze Angaben zur Breite der Radinfrastruktur',
    menuTitle: 'Wie ist die Breite',
    pubDate: '2025-01-01T15:00:00.000Z',
    visibility: 'secondary',
    category: 'width',
    description:
      'Diese Kampagne enthält Wege, bei denen die Angabe zur Breite der Radinfrastruktur fehlt.',
    task: '**Bitte ergänze die Breite der Radinfrastruktur `surface` und gerne auch die Breite der Radinfrastrukturnqualität `smoothness`.** Weitere Hinweise findet Du in der Aufgabenbeschreibung.',
    maprouletteChallenge: {
      discriminant: false,
    },
  },
  {
    id: 'needs_clarification',
    name: 'Die Radinfrastruktur konnte nicht kategorisiert werden (Alpha-Version)',
    menuTitle: 'Führungsform unklar',
    pubDate: '2025-01-01T15:00:00.000Z',
    visibility: 'promote',
    category: 'radinfra',
    description: 'Diese Kampagne enthält Radinfrastruktur die nicht kategorisiert werden konnte.',
    task: '**Bitte prüfe das Tagging und ergänze weitere Attribute, die bei der Kategorisierung helfen.** Weitere Hinweise findet Du in der Aufgabenbeschreibung.',
    maprouletteChallenge: {
      discriminant: true,
      value: {
        id: 50891,
        enabled: true,
        name: 'Führungsform der Radinfrastruktur unklar',
        resultsLimited: false,
      },
    },
  },
  {
    id: 'test_maproulette',
    name: 'Test Kampagne um MapRoulette Funktionen zu testen',
    menuTitle: 'Test MapRoulette Updates',
    pubDate: '2025-01-01T15:00:00.000Z',
    visibility: 'hidden',
    category: 'radinfra',
    description:
      'Mit dieser Kampagne test ich, wie sich MapRoulette verhält, wenn sich Daten extern ändern.',
    task: 'Hier gibt es nihts zu tun.',
    maprouletteChallenge: {
      discriminant: true,
      value: {
        id: 50884,
        enabled: false,
        name: 'Test MapRoulette Updates',
        resultsLimited: false,
      },
    },
  },
  {
    id: 'unexpected_bicycle_access_on_footway',
    name: 'Die Straßenklasse "Fußweg" ist unerwartet wenn Radinfrastruktur vorhanden ist (Alpha-Version)',
    menuTitle: 'Straßenklasse unklar (Fußweg)',
    pubDate: '2025-01-01T15:00:00.000Z',
    visibility: 'secondary',
    category: 'radinfra',
    description:
      'Diese Kampagne enthält Fußwege, die gleichzeitig Angaben zur Radinfrastruktur haben.',
    task: '**Bitte prüfe das Tagging; Eventuell ist eine andere Straßenklasse angebracht.** Weitere Hinweise findet Du in der Aufgabenbeschreibung.',
    maprouletteChallenge: {
      discriminant: true,
      value: {
        id: 50883,
        enabled: true,
        name: "Straßenklasse 'Fußweg' unklar",
        resultsLimited: false,
      },
    },
  },
]
