// DO NOT EDIT MANUALLY
// This file was automatically generated by `app/src/instrumentation/cacheRadinfraDeCampaigns.ts`
// To update, restart the server to trigger the instrumentation

import { RadinfraDeCampaignSchema } from './radinfraDeCampaignSchema'

export const radinfraDeCampaigns: RadinfraDeCampaignSchema[] = [
  {
    id: 'missing_access_tag_bicycle_road',
    name: 'Fahrradstraßen mit fehlendem `bicycle=designated`',
    menuTitle: 'Fahrradstraßen ohne Zusatzzeichen',
    pubDate: '2024-10-01T15:00:00.000Z',
    category: 'traffic_signs',
    maprouletteChallenge: {
      id: 49368,
      enabled: true,
      name: 'Fahrradstraßen mit fehlendem `bicycle=designated`',
    },
    description:
      'Diese Kampagne enthält Wege, die [im Radverkehrsatlas](https://radverkehrsatlas.de/) als Fahrradstraße klassifiziert sind, bei denen jedoch das `bicycle=designated` fehlt.',
    task: '**Bitte prüfe die Situation und ergänze den fehlenden Zugangs-Tag `bicycle=designated`.** Weitere Hinweise findet Du in der Aufgabenbeschreibung.',
  },
  {
    id: 'missing_traffic_sign_vehicle_destination',
    name: 'Fahrradstraßen ohne Zusatzzeichen »Anlieger frei«',
    menuTitle: 'Fahrradstraßen ohne Zusatzzeichen',
    pubDate: '2024-10-01T15:00:00.000Z',
    category: 'traffic_signs',
    maprouletteChallenge: {
      id: 49363,
      enabled: true,
      name: 'Fahrradstraßen ohne Zusatzzeichen »Anlieger frei«',
    },
    description:
      "Diese Kampagne enthält Wege, die [im Radverkehrsatlas](https://radverkehrsatlas.de/) als Fahrradstraße mit 'Anlieger frei'-Freigabe für Kfz kategorisiert wurden, jedoch fehlt das zugehörige Zusatzzeichen.",
    task: '**Bitte ergänze fehlende Verkehrszeichen oder ein explizites `traffic_sign=none`.** Weitere Hinweise findet Du in der Aufgabenbeschreibung.',
  },
  {
    id: 'missing_traffic_sign_244',
    name: 'Fahrradstraßen ohne Verkehrszeichen',
    menuTitle: 'Fahrradstraßen ohne Verkehrszeichen',
    pubDate: '2024-09-20T15:00:00.000Z',
    category: 'traffic_signs',
    maprouletteChallenge: {
      id: 49357,
      enabled: true,
      name: 'Fahrradstraßen ohne Verkehrszeichen',
    },
    description:
      'Diese Kampagne enthält Wege, die [im Radverkehrsatlas](https://radverkehrsatlas.de/) als Fahrradstraße kategorisiert wurden, jedoch fehlt das zugehörige Verkehrszeichen.',
    task: '**Bitte ergänze fehlende Verkehrszeichen oder ein explizites `traffic_sign=none`.** Weitere Hinweise findet Du in der Aufgabenbeschreibung.',
  },
]
