version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./app.Dockerfile
    entrypoint: /app/run.sh
    container_name: app
    environment:
      PGHOST:
      PGDATABASE: 
      PGUSER:
      PGPASSWORD:
      OSM_DOWNLOAD_URL:
      SKIP_DOWNLOAD:
      SKIP_TAG_FILTER:
      DEBUG:
      ID_FILTER:
      API_SECRET:
      ENVIRONMENT:
      SYNOLOGY_LOG_TOKEN:
      SYNOLOGY_ERROR_LOG_TOKEN:
    volumes:
      - osmfiles:/data
    depends_on:
      db:
        condition: service_healthy
    profiles:
      - osm_processing
  tiles:
    # There is no Apple M1 ARM 64 build, see https://github.com/CrunchyData/pg_tileserv/issues/127
    image: pramsey/pg_tileserv
    container_name: tiles
    environment:
      DATABASE_URL: postgres://${PGUSER}:${PGPASSWORD}@${PGHOST}/${PGDATABASE}
    ports:
      - 7800:7800
    depends_on:
      db:
        condition: service_healthy
  api:
    build:
      context: .
      dockerfile: ./api.Dockerfile
    container_name: api
    environment:
      PGHOST:
      PGDATABASE: 
      PGUSER:
      PGPASSWORD:
      API_SECRET:
    ports:
      - 80:80
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgis/postgis:14-3.3-alpine
    environment:
      PGUSER:
      POSTGRES_DB: ${PGDATABASE}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      LANG: en_US.UTF-8
      LC_ALL: en_US.UTF-8
    ports:
      - "5432:5432"
    volumes:
      - geodata:/var/lib/postgresql/data
    configs:
      - source: postgres_conf
        target: /postgresql/postgresql.conf
    command: ["-c", "config_file=/postgresql/postgresql.conf"]
    container_name: db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h ${PGHOST} -d ${PGDATABASE}"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  geodata:
  osmfiles:
configs:
  postgres_conf:
    file: ./postgres/postgres.development.conf
