services:
  traefik:
    image: traefik:v3.0
    container_name: traefik
    # Networking: See https://techoverflow.net/2021/06/11/how-to-fix-traefik-gateway-timeout-for-docker-services/ for network_mode
    restart: unless-stopped
    command:
      - "--log.level=WARN"
      - "--api.insecure=false"
      - "--api.dashboard=false"
      - "--providers.docker=true"
      # Do not expose containers unless explicitly told so
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.letsencrypt.acme.email=dev-team@fixmycity.de"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      - "--serversTransport.forwardingTimeouts.dialTimeout=100s"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "./letsencrypt:/letsencrypt"
    networks:
      - app_bridge
  proxy:
    image: nginx:alpine
    restart: unless-stopped
    container_name: tiles_proxy
    labels:
      traefik.enable: true
      traefik.http.routers.proxy.rule: Host(`${TILES_URL}`)
      traefik.http.routers.proxy.entrypoints: websecure
      traefik.http.routers.proxy.tls.certresolver: letsencrypt
      traefik.http.routers.proxy.tls: true
    ports:
      - "4444:80"
    volumes:
      - ./cache:/var/cache/nginx
      - ./logs:/var/log/nginx
    networks:
      - app_bridge
    configs:
      - source: nginx_conf
        target: /etc/nginx/nginx.conf

configs:
  nginx_conf:
    file: ./configs/nginx.conf
