version: "3"
services:
  app:
    image: public.ecr.aws/n0p8j4k5/tarmac/app:${GITHUB_SHA}
    entrypoint: /app/run.sh
    container_name: tarmac_staging
    environment:
      PGHOST:
      PGDATABASE:
      PGUSER:
      PGPASSWORD:
    volumes:
      - osmfiles:/data
  tiles:
    # There is no Apple M1 ARM 64 build, see https://github.com/CrunchyData/pg_tileserv/issues/127
    image: pramsey/pg_tileserv
    container_name: tileserver_staging
    restart: always
    environment:
      DATABASE_URL:
      NODE_ENV: production
    ports:
      - "9010:7800"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.stagingtiles.rule=Host(`staging-tiles.radverkehrsatlas.de`)"
      - "traefik.http.routers.stagingtiles.entrypoints=websecure"
      - "traefik.http.routers.stagingtiles.tls.certresolver=letsencrypt"
      - "traefik.http.routers.stagingtiles.tls=true"
  api:
    image: public.ecr.aws/n0p8j4k5/tarmac/api:${GITHUB_SHA}
    container_name: api_staging
    environment:
      PGHOST:
      PGDATABASE:
      PGUSER:
      PGPASSWORD:
    ports:
      - "9020:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.stagingapi.rule=Host(`staging-api.radverkehrsatlas.de`)"
      - "traefik.http.routers.stagingapi.entrypoints=websecure"
      - "traefik.http.routers.stagingapi.tls.certresolver=letsencrypt"
      - "traefik.http.routers.stagingapi.tls=true"
volumes:
  osmfiles_staging:
