version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./app.Dockerfile
    container_name: app
    environment:
      PGHOST:
      PGDATABASE:
      PGUSER:
      PGPASSWORD:
      OSM_DOWNLOAD_URL:
      SKIP_DOWNLOAD:
      SKIP_TAG_FILTER:
      SKIP_WARM_CACHE:
      WAIT_FOR_FRESH_DATA:
      ID_FILTER:
      API_SECRET:
      ENVIRONMENT:
      SYNOLOGY_LOG_TOKEN:
      SYNOLOGY_ERROR_LOG_TOKEN:
      TILES_URL:
      COMPUTE_DIFFS:
    volumes:
      - osmfiles:/data
      - geodata:/data/db
      - /var/run/docker.sock:/var/run/docker.sock
      - ./cache:/var/cache/nginx
      - ./configs/warm-cache.json:/app/warm-cache/config.json:ro
      - ./arguments:/app/arguments
    depends_on:
      db:
        condition: service_healthy
    profiles:
      - osm_processing
  tiles:
    # There is no Apple M1 ARM 64 build, see https://github.com/CrunchyData/pg_tileserv/issues/127
    image: ghcr.io/maplibre/martin
    container_name: tiles
    command: "--config /config.yaml"
    environment:
      DATABASE_URL: postgres://${PGUSER}:${PGPASSWORD}@${PGHOST}/${PGDATABASE}
      # https://maplibre.org/martin/troubleshooting.html?highlight=log#troubleshooting
      # RUST_LOG: actix_web=info,martin=debug,tokio_postgres=debug
      RUST_LOG: actix_web=info,martin=info,tokio_postgres=info
    ports:
      - 3000:3000
    volumes:
      - ./configs/martin.yaml:/config.yaml:ro
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgis/postgis:14-3.3-alpine
    shm_size: 1gb
    environment:
      PGUSER:
      POSTGRES_DB: ${PGDATABASE}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      LANG: en_US.UTF-8
      LC_ALL: en_US.UTF-8
    ports:
      - "5432:5432"
    volumes:
      - geodata:/var/lib/postgresql/data
    configs:
      - source: postgres_conf
        target: /postgresql/postgresql.conf
      - source: postgres_init
        target: /docker-entrypoint-initdb.d/11-postgres.sql
    command: ["-c", "config_file=/postgresql/postgresql.conf"]
    container_name: db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h ${PGHOST} -d ${PGDATABASE}"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  geodata:
  osmfiles:
configs:
  postgres_conf:
    file: ./configs/postgres.development.conf
  postgres_init:
    file: ./configs/postgres-init.sql
