version: "3"
services:
  app:
    env_file:
      - ./.env.production
    image: public.ecr.aws/n0p8j4k5/tarmac/app:${GITHUB_SHA}
    entrypoint: /app/run.sh
    container_name: app
    environment:
      SKIP_DOWNLOAD: 0
      SKIP_TAG_FILTER: 0
      OSM_DOWNLOAD_URL: http://download.geofabrik.de/europe/germany-latest.osm.pbf
    volumes:
      - osmfiles:/data
    networks:
      - app_bridge
    depends_on:
      db:
        condition: service_healthy
  tiles:
    # There is no Apple M1 ARM 64 build, see https://github.com/CrunchyData/pg_tileserv/issues/127
    image: pramsey/pg_tileserv
    env_file:
      - ./.env.production
    container_name: tiles
    restart: always
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://${PGUSER}:${PGPASSWORD_ENCODED}@${PGHOST}/${PGDATABASE}
    ports:
      - "8010:7800"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prodtiles.rule=Host(`tiles.radverkehrsatlas.de`)"
      - "traefik.http.routers.prodtiles.entrypoints=websecure"
      - "traefik.http.routers.prodtiles.tls.certresolver=letsencrypt"
      - "traefik.http.routers.prodtiles.tls=true"
      # HTTP & HTTPS Do not work simulatenously
      # - "traefik.http.routers.prodtiles.rule=Host(`tiles.radverkehrsatlas.de`)"
      # - "traefik.http.routers.prodtiles.entrypoints=web"
      # - "traefik.http.routers.service=prodtiles"
    networks:
      - radverkehrsatlas_mesh
      - app_bridge
    depends_on:
      db:
        condition: service_healthy
  api:
    env_file:
      - ./.env.production
    image: public.ecr.aws/n0p8j4k5/tarmac/api:${GITHUB_SHA}
    container_name: api
    restart: always
    ports:
      - "8020:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prodapi.rule=Host(`api.radverkehrsatlas.de`)"
      - "traefik.http.routers.prodapi.entrypoints=websecure"
      - "traefik.http.routers.prodapi.tls.certresolver=letsencrypt"
      - "traefik.http.routers.prodapi.tls=true"
    networks:
      - radverkehrsatlas_mesh
      - app_bridge
    depends_on:
      db:
        condition: service_healthy
  db:
      env_file:
        - ./.env.production
      image: postgis/postgis:14-3.3-alpine
      environment:
        POSTGRES_DB: ${PGDATABASE}
        POSTGRES_USER: ${PGUSER}
        POSTGRES_PASSWORD: ${PGPASSWORD}
        LANG: en_US.UTF-8
        LC_ALL: en_US.UTF-8
      ports:
        - "6000:5432"
      volumes:
        - geodata:/var/lib/postgresql/data
      container_name: db
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 5s
        timeout: 5s
        retries: 5
      networks:
        - app_bridge
volumes:
  osmfiles:
  geodata:
networks:
  radverkehrsatlas_mesh:
    external: true
  app_bridge:
