-- Learn more about this file in README.md

-- DROP TABLE IF EXISTS _roadtypesOsm_buffer;
-- DROP TABLE IF EXISTS amenity_parking_points;
-- DROP TABLE IF EXISTS bicycleRoadInfrastructure;
-- DROP TABLE IF EXISTS bicycleRoadInfrastructure_skipList;
-- DROP TABLE IF EXISTS boundaries;
-- DROP TABLE IF EXISTS crossings;
-- DROP TABLE IF EXISTS footways;
-- DROP TABLE IF EXISTS footways_tmp;
-- DROP TABLE IF EXISTS fromTo_education;
DROP TABLE IF EXISTS fromTo_landuse;
-- DROP TABLE IF EXISTS fromTo_publicTransport;
-- DROP TABLE IF EXISTS fromTo_shopping;
-- DROP TABLE IF EXISTS fromTo_shopping_todoList;
-- DROP TABLE IF EXISTS highways;
-- DROP TABLE IF EXISTS lit;
-- DROP TABLE IF EXISTS metadata;
-- DROP TABLE IF EXISTS parking_poly;
-- DROP TABLE IF EXISTS places;
-- DROP TABLE IF EXISTS places_todoList;
-- DROP TABLE IF EXISTS pt_platform;
-- DROP TABLE IF EXISTS pt_stops;
-- DROP TABLE IF EXISTS ramps;
-- DROP TABLE IF EXISTS roadtypesOsm;
-- DROP TABLE IF EXISTS roadtypesOsm_skipList;
-- DROP TABLE IF EXISTS service;
-- DROP TABLE IF EXISTS service_tmp;
-- DROP TABLE IF EXISTS traffic_calming_points;
