// Autogenerated by `scripts/MapboxStyles/process.ts`
// Do not change this file manually

import { MapboxStyleLayer } from '../types'

export const mapboxStyleGroupLayers_atlas_bikelanes_details: MapboxStyleLayer[] = [
  {
    id: 'needsClarification-details',
    type: 'line',
    paint: {
      'line-width': ['interpolate', ['linear'], ['zoom'], 10, 1.5, 14, 2, 16, 3],
      'line-color': '#b50382',
      'line-dasharray': [2.5, 0.5],
    },
    filter: [
      'match',
      ['get', 'category'],
      [
        'needsClarification',
        'footwayBicycleYes_adjoiningOrIsolated',
        'footAndCyclewayShared_adjoiningOrIsolated',
        'footAndCyclewaySegregated_adjoiningOrIsolated',
      ],
      true,
      false,
    ],
  },
  {
    id: 'todo--oneway-no-icon copy 1',
    type: 'line',
    paint: {},
    filter: ['all', ['has', 'category'], ['match', ['get', 'oneway'], ['no'], true, false]],
  },
  {
    id: 'shared-kfzlane',
    type: 'line',
    paint: {
      'line-width': ['interpolate', ['linear'], ['zoom'], 10, 1.5, 14, 2, 16, 3],
      'line-color': '#059669',
      'line-offset': ['interpolate', ['linear'], ['zoom'], 12, 0, 15, -1],
      'line-dasharray': [2, 1],
    },
    filter: ['match', ['get', 'category'], ['sharedMotorVehicleLane'], true, false],
  },
  {
    id: 'shared-buslane',
    type: 'line',
    paint: {
      'line-width': ['interpolate', ['linear'], ['zoom'], 10, 1.5, 14, 2, 16, 3],
      'line-color': '#059669',
      'line-offset': ['interpolate', ['linear'], ['zoom'], 12, 0, 15, -1],
    },
    filter: ['match', ['get', 'category'], ['sharedBusLane'], true, false],
  },
  {
    id: 'bikeroad',
    type: 'line',
    paint: {
      'line-width': ['interpolate', ['linear'], ['zoom'], 10, 1.5, 14, 2, 16, 3],
      'line-color': '#fb923c',
      'line-offset': ['interpolate', ['linear'], ['zoom'], 12, 0, 15, -1],
    },
    filter: ['match', ['get', 'category'], ['bicycleRoad_vehicleDestination'], true, false],
  },
  {
    id: 'footway-bikefree',
    type: 'line',
    paint: {
      'line-width': ['interpolate', ['linear'], ['zoom'], 10, 1.5, 14, 2, 16, 3],
      'line-dasharray': [2, 1],
      'line-color': '#ec4899',
      'line-offset': ['interpolate', ['linear'], ['zoom'], 12, 0, 15, -1],
    },
    filter: [
      'match',
      ['get', 'category'],
      ['pedestrianAreaBicycleYes', 'footwayBicycleYes_isolated'],
      true,
      false,
    ],
  },
  {
    id: 'shared--sidepath',
    type: 'line',
    paint: {
      'line-width': ['interpolate', ['linear'], ['zoom'], 10, 1.5, 14, 2, 16, 3],
      'line-color': '#ec4899',
      'line-offset': ['interpolate', ['linear'], ['zoom'], 12, 0, 15, -1],
    },
    filter: [
      'match',
      ['get', 'category'],
      ['footAndCyclewayShared_adjoining', 'footAndCyclewayShared_isolated'],
      true,
      false,
    ],
  },
  {
    id: 'separated-lane-dashed',
    type: 'line',
    paint: {
      'line-width': ['interpolate', ['linear'], ['zoom'], 10, 1.5, 14, 2, 16, 3],
      'line-color': '#2dd4bf',
      'line-offset': ['interpolate', ['linear'], ['zoom'], 12, 0, 15, -1],
    },
    filter: [
      'all',
      [
        'match',
        ['get', 'category'],
        [
          'cyclewayLink',
          'cyclewayOnHighwayBetweenLanes',
          'cyclewayOnHighway_exclusive',
          'crossing',
          'cyclewayOnHighway_advisory',
        ],
        true,
        false,
      ],
      [
        'match',
        ['get', 'separation:left'],
        ['dashed_line', 'dashed_line;kerb', 'dashed_line;parking_lane', 'dashed_lane'],
        true,
        false,
      ],
    ],
  },
  {
    filter: [
      'all',
      [
        'match',
        ['get', 'category'],
        [
          'cyclewayLink',
          'cyclewayOnHighwayBetweenLanes',
          'cyclewayOnHighway_exclusive',
          'crossing',
          'cyclewayOnHighway_advisory',
        ],
        true,
        false,
      ],
      [
        'match',
        ['get', 'separation:left'],
        [
          'solid_lane',
          'solid_line;parking_lane',
          'solid_line',
          'bollard;parking_lane',
          'separation_kerb;parking_lane',
          'separation_kerb;vertical_panel',
          'planter',
          'bump',
          'vertical_panel',
          'bollard;kerb',
          'flex_post',
        ],
        true,
        false,
      ],
    ],
    type: 'line',
    id: 'separated-lane',
    paint: {
      'line-width': ['interpolate', ['linear'], ['zoom'], 10, 1.5, 14, 2, 16, 3],
      'line-color': '#2dd4bf',
      'line-offset': ['interpolate', ['linear'], ['zoom'], 12, 0, 15, -1],
    },
  },
  {
    filter: [
      'match',
      ['get', 'category'],
      ['footAndCyclewaySegregated_adjoining', 'footAndCyclewaySegregated_adjoiningOrIsolated'],
      true,
      false,
    ],
    type: 'line',
    id: 'separated-sidepath',
    paint: {
      'line-width': ['interpolate', ['linear'], ['zoom'], 10, 1.5, 14, 2, 16, 3],
      'line-color': '#174ed9',
      'line-offset': ['interpolate', ['linear'], ['zoom'], 12, 0, 15, -1],
    },
  },
  {
    id: 'separated-free',
    type: 'line',
    paint: {
      'line-width': ['interpolate', ['linear'], ['zoom'], 10, 1.5, 14, 2, 16, 3],
      'line-color': '#818cf8',
      'line-offset': ['interpolate', ['linear'], ['zoom'], 12, 0, 15, -1],
    },
    filter: [
      'match',
      ['get', 'category'],
      ['cycleway_isolated', 'cycleway_adjoining', 'bicycleRoad'],
      true,
      false,
    ],
  },
  {
    id: 'hitarea-bikelanes copy 1',
    type: 'line',
    paint: {
      'line-width': ['interpolate', ['linear'], ['zoom'], 9, 1, 14.1, 10, 22, 12],
      'line-opacity': 0,
      'line-color': 'hsl(290, 100%, 54%)',
    },
    filter: ['has', 'category'],
    layout: {
      'line-cap': 'round',
    },
  },
]
