// Autogenerated by `scripts/MapboxStyles/process.ts`
// Do not change this file manually

import { MapboxStyleLayer } from '../types'

export const mapboxStyleGroupLayers_atlas_barriers__area: MapboxStyleLayer[] = [
  {
    id: 'barriers_water_aerodrome2',
    type: 'fill',
    paint: {
      'fill-opacity': 0.42,
    },
  },
  {
    id: 'barriers_water_aerodrome',
    type: 'fill',
    paint: {
      'fill-opacity': 0.5,
      'fill-translate': [0, 0],
      'fill-pattern': 'cross-hatch-barriers',
    },
  },
]
