// Autogenerated by `scripts/MapboxStyles/process.ts`
// Do not change this file manually

import { MapboxStyleLayer } from '../types'

export const mapboxStyleGroupLayers_atlas_bikelane_presence: MapboxStyleLayer[] = [
  {
    filter: ['has', 'bikelane_right'],
    type: 'line',
    id: 'bikelane_right',
    paint: {
      'line-color': [
        'case',
        ['match', ['get', 'bikelane_right'], ['missing'], true, false],
        'rgb(250, 128, 225)',
        ['match', ['get', 'bikelane_right'], ['not_expected'], true, false],
        'rgba(230, 230, 230, 0.68)',
        ['match', ['get', 'bikelane_right'], ['data_no'], true, false],
        'rgba(248, 216, 216, 0.67)',
        ['has', 'bikelane_right'],
        'rgba(235, 235, 254, 0.7)',
        'rgba(0, 0, 0, 0.7)',
      ],
      'line-offset': ['step', ['zoom'], 2, 14, 4],
      'line-width': ['step', ['zoom'], 2, 14, 4],
    },
  },
  {
    filter: ['has', 'bikelane_self'],
    type: 'line',
    id: 'bikelane_self',
    paint: {
      'line-color': [
        'case',
        ['match', ['get', 'bikelane_self'], ['missing'], true, false],
        'rgb(250, 128, 225)',
        ['match', ['get', 'bikelane_self'], ['not_expected'], true, false],
        'rgba(230, 230, 230, 0.68)',
        ['match', ['get', 'bikelane_self'], ['data_no'], true, false],
        'rgba(248, 216, 216, 0.67)',
        ['has', 'bikelane_self'],
        'rgba(235, 235, 254, 0.7)',
        'rgba(0, 0, 0, 0.7)',
      ],
      'line-offset': ['step', ['zoom'], 2, 14, 4],
      'line-width': ['step', ['zoom'], 2, 14, 4],
    },
  },
  {
    filter: ['has', 'bikelane_left'],
    type: 'line',
    id: 'bilelane_left',
    paint: {
      'line-color': [
        'case',
        ['match', ['get', 'bikelane_left'], ['missing'], true, false],
        'rgb(250, 128, 225)',
        ['match', ['get', 'bikelane_left'], ['not_expected'], true, false],
        'rgba(230, 230, 230, 0.68)',
        ['match', ['get', 'bikelane_left'], ['data_no'], true, false],
        'rgba(248, 216, 216, 0.67)',
        ['has', 'bikelane_left'],
        'rgba(235, 235, 254, 0.7)',
        'rgba(0, 0, 0, 0.7)',
      ],
      'line-offset': ['step', ['zoom'], -2, 14, -4],
      'line-width': ['step', ['zoom'], 2, 14, 4],
    },
  },
]
