// Autogenerated by `scripts/MapboxStyles/process.ts`
// Do not change this file manually

import { MapboxStyleLayer } from '../types'

export const mapboxStyleGroupLayers_atlas_barriers__line: MapboxStyleLayer[] = [
  {
    minzoom: 9,
    filter: ['has', 'highway'],
    type: 'line',
    id: 'barriers-motorway',
    paint: {
      'line-color': [
        'case',
        [
          'match',
          ['get', 'highway'],
          ['motorway', 'motorway_link', 'trunk', 'trunk_link'],
          true,
          false,
        ],
        'hsl(0, 0%, 3%)',
        'rgba(235, 0, 0, 0)',
      ],
      'line-width': ['interpolate', ['linear'], ['zoom'], 10, 2, 18, 4],
      'line-opacity': 0.64,
    },
  },
  {
    id: 'railway-rail',
    type: 'line',
    filter: ['match', ['get', 'railway'], ['rail'], true, false],
    paint: {
      'line-color': 'hsl(300, 88%, 10%)',
      'line-width': ['interpolate', ['linear'], ['zoom'], 10, 2, 18, 4],
    },
  },
  {
    id: 'railway_rail-white',
    type: 'line',
    filter: ['match', ['get', 'railway'], ['rail'], true, false],
    paint: {
      'line-color': 'hsl(300, 4%, 97%)',
      'line-width': ['interpolate', ['linear'], ['zoom'], 10, 1.8, 18, 3.8],
      'line-dasharray': [1, 1.1],
    },
  },
  {
    id: 'railway_light_rail',
    type: 'line',
    filter: ['match', ['get', 'railway'], ['light_rail'], true, false],
    paint: {
      'line-color': 'hsl(300, 88%, 10%)',
      'line-width': ['interpolate', ['linear'], ['zoom'], 10, 1, 18, 2],
    },
  },
  {
    id: 'railway_light_rail-white',
    type: 'line',
    filter: ['match', ['get', 'railway'], ['light_rail'], true, false],
    paint: {
      'line-color': 'hsl(300, 4%, 97%)',
      'line-width': ['interpolate', ['linear'], ['zoom'], 10, 0.8, 18, 1.8],
      'line-dasharray': [1.2, 1.4],
    },
  },
]
