// Autogenerated by `scripts/MapboxStyles/process.ts`
// Do not change this file manually

import { MapboxStyleLayer } from '../types'

export const mapboxStyleGroupLayers_atlas_zieleplubarriers: MapboxStyleLayer[] = [
  {
    layout: {},
    filter: ['match', ['get', 'waterway'], ['river', 'canal'], false, true],
    type: 'line',
    id: 'atlas-barrierlines-3ft1bu',
    paint: {
      'line-color': ['match', ['get', 'railway'], ['rail', 'light_rail'], '#6a0e81', '#3d3d3d'],
    },
  },
  {
    type: 'fill',
    id: 'atlas-barrierareas-b9mb1o',
    paint: {
      'fill-opacity': 0.7,
      'fill-translate': [0, 0],
      'fill-pattern': 'basics-textures-cross-hatch-fine',
    },
    layout: {},
  },
]
