// Autogenerated by `scripts/MapboxStyles/process.ts`
// Do not change this file manually

import { MapboxStyleLayer } from '../types'

export const mapboxStyleGroupLayers_atlas_old_bikelanespresence_complete: MapboxStyleLayer[] = [
  {
    type: 'line',
    id: 'left',
    paint: {
      'line-color': [
        'case',
        ['match', ['get', 'left'], ['missing'], true, false],
        'rgb(250, 128, 225)',
        ['match', ['get', 'left'], ['not_expected'], true, false],
        'rgba(230, 230, 230, 0.68)',
        ['match', ['get', 'left'], ['data_no'], true, false],
        'rgba(248, 216, 216, 0.67)',
        ['has', 'left'],
        'rgba(235, 235, 254, 0.7)',
        'rgba(0, 0, 0, 0.7)',
      ],
      'line-width': ['step', ['zoom'], 2, 14, 4],
      'line-offset': ['step', ['zoom'], -2, 14, -4],
    },
    layout: {},
  },
  {
    type: 'line',
    id: 'self',
    paint: {
      'line-color': [
        'case',
        ['match', ['get', 'self'], ['missing'], true, false],
        'rgb(250, 128, 225)',
        ['match', ['get', 'self'], ['not_expected'], true, false],
        'rgba(230, 230, 230, 0.68)',
        ['match', ['get', 'self'], ['data_no'], true, false],
        'rgba(248, 216, 216, 0.67)',
        ['has', 'self'],
        'rgba(235, 235, 254, 0.7)',
        'rgba(0, 0, 0, 0.7)',
      ],
      'line-width': ['step', ['zoom'], 2, 14, 4],
    },
    layout: {},
  },
  {
    type: 'line',
    id: 'right',
    paint: {
      'line-color': [
        'case',
        ['match', ['get', 'right'], ['missing'], true, false],
        'rgb(250, 128, 225)',
        ['match', ['get', 'right'], ['not_expected'], true, false],
        'rgba(230, 230, 230, 0.68)',
        ['match', ['get', 'right'], ['data_no'], true, false],
        'rgba(248, 216, 216, 0.67)',
        ['has', 'right'],
        'rgba(235, 235, 254, 0.7)',
        'rgba(0, 0, 0, 0.7)',
      ],
      'line-offset': ['step', ['zoom'], 2, 14, 4],
      'line-width': ['step', ['zoom'], 2, 14, 4],
    },
    layout: {},
  },
]
