// Autogenerated by `scripts/MapboxStyles/process.ts`
// Do not change this file manually

import { MapboxStyleLayer } from '../types'

export const mapboxStyleGroupLayers_atlas_roadclassification_plus_fusswege: MapboxStyleLayer[] = [
  {
    minzoom: 13,
    layout: {},
    filter: [
      'match',
      ['get', 'road'],
      ['path', 'track', 'bridleway', 'footway', 'cycleway'],
      true,
      false,
    ],
    type: 'line',
    id: 'roadclassification-nokfz',
    paint: {
      'line-color': [
        'case',
        ['match', ['get', 'road'], ['track', 'bridleway'], true, false],
        '#b4aac0',
        ['match', ['get', 'road'], ['path', 'footway', 'cycleway'], true, false],
        '#c6aed0',
        'rgba(192, 191, 191, 0.75)',
      ],
      'line-width': 0.7,
    },
  },
  {
    layout: {
      'line-cap': 'round',
    },
    filter: [
      'match',
      ['get', 'road'],
      ['path', 'track', 'bridleway', 'footway', 'cycleway'],
      true,
      false,
    ],
    type: 'line',
    id: 'hitarea-roadclassification_plus_fusswege',
    paint: {
      'line-width': ['interpolate', ['linear'], ['zoom'], 9, 1, 14.1, 10, 22, 12],
      'line-opacity': 0,
      'line-color': 'rgb(216, 20, 255)',
    },
  },
]
