// Autogenerated by `scripts/MapboxStyles/process.ts`
// Do not change this file manually

import { MapboxStyleLayer } from '../types'

export const mapboxStyleGroupLayers_atlas_maxspeed_presence: MapboxStyleLayer[] = [
  {
    layout: {
      'line-cap': 'round',
    },
    type: 'line',
    id: 'maxspeed_presence',
    paint: {
      'line-opacity': 0.98,
      'line-width': ['interpolate', ['linear'], ['zoom'], 11, 0.5, 15, 1],
      'line-color': ['case', ['has', 'maxspeed'], '#000000', '#ca1212'],
    },
  },
  {
    layout: {
      'line-cap': 'round',
    },
    type: 'line',
    id: 'hitarea-maxspeed-presence',
    paint: {
      'line-width': ['interpolate', ['linear'], ['zoom'], 9, 1, 14.1, 10, 22, 12],
      'line-opacity': 0,
      'line-color': 'rgb(216, 20, 255)',
    },
  },
]
