// Autogenerated by `scripts/MapboxStyles/process.ts`
// Do not change this file manually

import { MapboxStyleLayer } from '../types'

export const mapboxStyleGroupLayers_atlas_ziele_plus_publictransport: MapboxStyleLayer[] = [
  {
    layout: {
      'icon-image': [
        'match',
        ['get', 'station'],
        ['subway'],
        'de-u-bahn',
        ['light_rail'],
        'de-s-bahn',
        ['train'],
        'boston-t',
        'border-dot-13',
      ],
      'icon-padding': 1,
      'icon-allow-overlap': true,
    },
    filter: ['has', 'station'],
    type: 'symbol',
    id: 'publictransport',
    paint: {},
  },
]
