// Autogenerated by `scripts/MapboxStyles/process.ts`
// Do not change this file manually

import { MapboxStyleLayer } from '../types'

export const mapboxStyleGroupLayers_atlas_bikelanes_default: MapboxStyleLayer[] = [
  {
    id: 'needsClarification',
    type: 'line',
    paint: {
      'line-width': ['interpolate', ['linear'], ['zoom'], 8, 1.5, 10, 1.5, 14, 2, 16, 3],
      'line-color': '#a97bea',
      'line-dasharray': [2.5, 0.5],
    },
    filter: [
      'match',
      ['get', 'category'],
      ['needsClarification', 'footwayBicycleYes_adjoiningOrIsolated'],
      true,
      false,
    ],
  },
  {
    id: 'todo--oneway-no-icon',
    type: 'line',
    paint: {},
    filter: ['all', ['has', 'category'], ['match', ['get', 'oneway'], ['no'], true, false]],
  },
  {
    id: 'shared-fahrbahn',
    type: 'line',
    paint: {
      'line-width': ['interpolate', ['linear'], ['zoom'], 8, 1.5, 10, 1.5, 14, 2, 16, 3],
      'line-dasharray': [3, 1],
      'line-color': '#0098f0',
      'line-offset': ['interpolate', ['linear'], ['zoom'], 12, 0, 15, -1],
    },
    filter: [
      'match',
      ['get', 'category'],
      ['sharedBusLane', 'sharedMotorVehicleLane', 'bicycleRoad_vehicleDestination'],
      true,
      false,
    ],
  },
  {
    id: 'shared-seitenraum',
    type: 'line',
    paint: {
      'line-width': ['interpolate', ['linear'], ['zoom'], 8, 1.5, 10, 1.5, 14, 2, 16, 3],
      'line-dasharray': [3, 1],
      'line-color': '#174ed9',
      'line-offset': ['interpolate', ['linear'], ['zoom'], 12, 0, 15, -1],
    },
    filter: [
      'match',
      ['get', 'category'],
      [
        'footAndCyclewayShared_isolated',
        'footAndCyclewayShared_adjoining',
        'footAndCyclewayShared_adjoiningOrIsolated',
        'footwayBicycleYes_isolated',
        'pedestrianAreaBicycleYes',
      ],
      true,
      false,
    ],
  },
  {
    id: 'separated-fahrbahn',
    type: 'line',
    paint: {
      'line-width': ['interpolate', ['linear'], ['zoom'], 8, 1.5, 10, 1.5, 14, 2, 16, 3],
      'line-color': '#0098f0',
      'line-offset': ['interpolate', ['linear'], ['zoom'], 12, 0, 15, -1],
    },
    filter: [
      'match',
      ['get', 'category'],
      [
        'cyclewayOnHighway_exclusive',
        'cyclewayOnHighwayBetweenLanes',
        'cyclewayLink',
        'crossing',
        'cyclewayOnHighway_advisory',
      ],
      true,
      false,
    ],
  },
  {
    id: 'separated-seitenraum und frei',
    type: 'line',
    paint: {
      'line-width': ['interpolate', ['linear'], ['zoom'], 8, 1.5, 10, 1.5, 14, 2, 16, 3],
      'line-color': '#174ed9',
      'line-offset': ['interpolate', ['linear'], ['zoom'], 12, 0, 15, -1],
    },
    filter: [
      'match',
      ['get', 'category'],
      [
        'footAndCyclewaySegregated_adjoining',
        'footAndCyclewaySegregated_adjoiningOrIsolated',
        'cycleway_isolated',
        'cycleway_adjoining',
        'bicycleRoad',
      ],
      true,
      false,
    ],
  },
  {
    id: 'hitarea-bikelanes',
    type: 'line',
    paint: {
      'line-width': ['interpolate', ['linear'], ['zoom'], 9, 1, 14.1, 10, 22, 12],
      'line-opacity': 0,
      'line-color': 'hsl(290, 100%, 54%)',
    },
    filter: ['has', 'category'],
    layout: {
      'line-cap': 'round',
    },
  },
]
