// Autogenerated by `scripts/MapboxStyles/process.ts`
// Do not change this file manually

import { MapboxStyleLayer } from '../types'

export const mapboxStyleGroupLayers_atlas_lit_fresh: MapboxStyleLayer[] = [
  {
    filter: [
      'all',
      ['match', ['get', 'lit'], ['yes'], true, false],
      ['match', ['get', 'area'], ['yes'], true, false],
    ],
    type: 'fill',
    id: 'lit-fresh-area',
    paint: {
      'fill-color': [
        'match',
        ['get', 'lit_fresh'],
        ['outdated_update_at', 'outdated_check_date'],
        'rgb(209, 0, 0)',
        ['fresh_update_at', 'fresh_check_date'],
        'rgb(91, 242, 49)',
        'rgba(0, 0, 0, 0)',
      ],
      'fill-opacity': 0.2,
    },
  },
  {
    layout: {
      'line-cap': 'round',
    },
    filter: ['match', ['get', 'lit'], ['yes'], true, false],
    type: 'line',
    id: 'lit-fresh-line',
    paint: {
      'line-width': ['interpolate', ['linear'], ['zoom'], 12, 3, 18, 4],
      'line-color': [
        'match',
        ['get', 'lit_fresh'],
        ['outdated_update_at', 'outdated_check_date'],
        'rgb(209, 0, 0)',
        ['fresh_update_at', 'fresh_check_date'],
        'rgb(91, 242, 49)',
        'rgba(0, 0, 0, 0)',
      ],
      'line-opacity': ['interpolate', ['linear'], ['zoom'], 13, 0.8, 18, 0.6],
      'line-blur': 1,
      'line-offset': ['interpolate', ['linear'], ['zoom'], 12, 1.5, 18, 5],
    },
  },
]
