// Autogenerated by `scripts/MapboxStyles/process.ts`
// Do not change this file manually

import { MapboxStyleLayer } from '../types'

export const mapboxStyleGroupLayers_atlas_maxspeed_all: MapboxStyleLayer[] = [
  {
    layout: {
      'line-cap': 'round',
    },
    filter: ['has', 'maxspeed'],
    type: 'line',
    id: 'maxspeed-50-80',
    paint: {
      'line-opacity': 0.98,
      'line-color': [
        'interpolate',
        ['linear'],
        ['get', 'maxspeed'],
        20,
        '#08aec4',
        30,
        '#2cb587',
        40,
        '#eeb449',
        50,
        '#fc7c40',
        60,
        '#e92d07',
        80,
        '#b80505',
      ],
      'line-width': ['interpolate', ['linear'], ['zoom'], 11, 0.5, 15, 1],
    },
  },
  {
    layout: {
      'line-cap': 'round',
    },
    filter: ['has', 'maxspeed'],
    type: 'line',
    id: 'hitarea-maxspeed-all',
    paint: {
      'line-width': ['interpolate', ['linear'], ['zoom'], 9, 1, 14.1, 10, 22, 12],
      'line-opacity': 0,
      'line-color': 'rgb(216, 20, 255)',
    },
  },
]
