// Autogenerated by `scripts/MapboxStyles/process.ts`
// Do not change this file manually

import { MapboxStyleLayer } from '../types'

export const mapboxStyleGroupLayers_atlas_bikelanes_plus_routes: MapboxStyleLayer[] = [
  {
    layout: {
      'line-cap': 'round',
      'line-join': 'round',
    },
    type: 'line',
    id: 'route',
    paint: {
      'line-color': '#3dc8ff',
      'line-width': ['interpolate', ['linear'], ['zoom'], 5, 2, 15, 15],
      'line-opacity': 0.4,
      'line-blur': ['interpolate', ['linear'], ['zoom'], 5, 0, 15, 8],
    },
  },
  {
    layout: {
      'text-size': 10,
      'icon-image': 'de-motorway-2',
      'text-transform': 'uppercase',
      'symbol-spacing': 700,
      'text-font': ['Open Sans Bold', 'Arial Unicode MS Regular'],
      'symbol-placement': 'line',
      'icon-size': 1.5,
      'text-field': ['to-string', ['get', 'ref']],
      'text-letter-spacing': -0.02,
    },
    filter: ['has', 'ref'],
    type: 'symbol',
    id: 'sign_label',
    paint: {
      'text-color': '#c7efff',
      'icon-opacity': 0.9,
    },
  },
]
