// Autogenerated by `scripts/MapboxStyles/process.ts`
// Do not change this file manually

import { MapboxStyleLayer } from '../types'

export const mapboxStyleGroupLayers_atlas_boundaries_names: MapboxStyleLayer[] = [
  {
    type: 'symbol',
    id: 'admin-level-8-9-10 name',
    paint: {
      'text-halo-color': '#e8e8e8',
      'text-halo-width': 1,
      'text-color': '#6c3d3d',
    },
    layout: {
      'text-field': ['to-string', ['get', 'name']],
      'text-size': ['interpolate', ['linear'], ['zoom'], 8, 8, 11, 12],
    },
    filter: [
      'all',
      ['match', ['get', 'admin_level'], ['10', '9', '8'], true, false],
      ['match', ['geometry-type'], ['Polygon'], true, false],
    ],
  },
  {
    type: 'symbol',
    id: 'admin-level-7 name',
    paint: {
      'text-halo-color': '#e8e8e8',
      'text-halo-width': 1,
      'text-color': '#6c3d3d',
    },
    layout: {
      'text-field': ['to-string', ['get', 'name']],
      'text-size': ['interpolate', ['linear'], ['zoom'], 8, 8, 11, 12],
    },
    filter: [
      'all',
      ['match', ['get', 'admin_level'], ['7'], true, false],
      ['match', ['geometry-type'], ['Polygon'], true, false],
    ],
  },
]
