// Autogenerated by `scripts/MapboxStyles/process.ts`
// Do not change this file manually

import { MapboxStyleLayer } from '../types'

export const mapboxStyleGroupLayers_atlas_surface_present: MapboxStyleLayer[] = [
  {
    filter: ['has', 'surface'],
    type: 'line',
    id: 'surface-present',
    paint: {
      'line-width': ['interpolate', ['linear'], ['zoom'], 12, 1, 14, 1.5, 18, 3],
      'line-color': 'hsl(312, 0%, 34%)',
      'line-opacity': 0.7,
    },
  },
  {
    filter: ['!', ['has', 'surface']],
    type: 'line',
    id: 'surface-missing',
    paint: {
      'line-width': ['interpolate', ['linear'], ['zoom'], 12, 1, 14, 1.5, 18, 3],
      'line-color': 'hsl(312, 92%, 74%)',
      'line-opacity': 0.7,
    },
  },
]
