// Autogenerated by `scripts/MapboxStyles/process.ts`
// Do not change this file manually

import { MapboxStyleLayer } from '../types'

export const mapboxStyleGroupLayers_atlas_surface_fresh: MapboxStyleLayer[] = [
  {
    filter: [
      'match',
      ['get', 'smoothness_fresh'],
      ['fresh_check_date', 'fresh_update_at'],
      true,
      false,
    ],
    type: 'line',
    id: 'smoothness-fresh',
    paint: {
      'line-color': 'hsl(107, 88%, 57%)',
      'line-width': ['interpolate', ['linear'], ['zoom'], 7, 2, 12, 4, 16, 12],
      'line-dasharray': [1, 1],
    },
  },
  {
    filter: [
      'match',
      ['get', 'surface_fresh'],
      ['fresh_check_date', 'fresh_update_at'],
      true,
      false,
    ],
    type: 'line',
    id: 'surface-fresh',
    paint: {
      'line-color': 'hsl(107, 88%, 57%)',
      'line-width': ['interpolate', ['linear'], ['zoom'], 7, 2, 12, 4, 16, 12],
    },
  },
  {
    filter: [
      'match',
      ['get', 'smoothness_fresh'],
      ['outdated_check_date', 'outdated_update_at'],
      true,
      false,
    ],
    type: 'line',
    id: 'smoothness-outdated',
    paint: {
      'line-color': 'hsl(0, 100%, 41%)',
      'line-width': ['interpolate', ['linear'], ['zoom'], 7, 2, 12, 4, 16, 12],
      'line-dasharray': [1, 1],
    },
  },
  {
    filter: [
      'match',
      ['get', 'surface_fresh'],
      ['outdated_check_date', 'outdated_update_at'],
      true,
      false,
    ],
    type: 'line',
    id: 'surface-outdated',
    paint: {
      'line-color': 'hsl(0, 100%, 41%)',
      'line-width': ['interpolate', ['linear'], ['zoom'], 7, 2, 12, 4, 16, 12],
    },
  },
]
