// Autogenerated by `scripts/MapboxStyles/process.ts`
// Do not change this file manually

import { MapboxStyleLayer } from '../types'

export const mapboxStyleGroupLayers_atlas_ziele_plus_publictransport: MapboxStyleLayer[] = [
  {
    layout: {
      'icon-image': [
        'match',
        ['get', 'category'],
        ['ferry_station'],
        'ferry',
        ['railway_station'],
        'singapore-mrt',
        '',
      ],
      'icon-padding': 1,
      'icon-allow-overlap': true,
      'icon-size': ['match', ['get', 'category'], ['ferry_station'], 0.8, 1],
    },
    filter: ['has', 'category'],
    type: 'symbol',
    id: 'publictransport',
    paint: {
      'icon-opacity': [
        'interpolate',
        ['linear'],
        ['zoom'],
        8,
        ['match', ['get', 'category'], ['railway_station'], 1, 0],
        10,
        ['match', ['get', 'category'], ['railway_station'], 1, 0],
        10.1,
        1,
      ],
    },
  },
]
