// Autogenerated by `scripts/MapboxStyles/process.ts`
// Do not change this file manually

import { MapboxStyleLayer } from '../types'

export const mapboxStyleGroupLayers_atlas_roads_plus_label: MapboxStyleLayer[] = [
  {
    layout: {
      'text-size': 9,
      'icon-text-fit': 'width',
      'icon-image': 'rectangle-yellow-3',
      'icon-rotation-alignment': 'viewport',
      'text-transform': 'uppercase',
      'symbol-spacing': 700,
      'text-font': ['Open Sans Bold', 'Arial Unicode MS Regular'],
      'symbol-placement': 'line',
      'text-rotation-alignment': 'viewport',
      'icon-size': 1.2,
      'text-field': ['to-string', ['get', 'name_ref']],
      'text-letter-spacing': -0.02,
      'icon-padding': 6,
    },
    type: 'symbol',
    id: 'sign_label-roads',
    paint: {
      'text-color': '#595959',
      'icon-opacity': [
        'interpolate',
        ['linear'],
        ['zoom'],
        8,
        ['match', ['get', 'network'], ['ncn'], 1, 0],
        9.4,
        ['match', ['get', 'network'], ['ncn'], 1, 0],
        9.5,
        1,
      ],
      'text-opacity': [
        'interpolate',
        ['linear'],
        ['zoom'],
        8,
        ['match', ['get', 'network'], ['ncn'], 1, 0],
        9.4,
        ['match', ['get', 'network'], ['ncn'], 1, 0],
        9.5,
        1,
      ],
    },
    filter: [
      'all',
      [
        'match',
        ['get', 'road'],
        ['primary', 'primary_link', 'secondary', 'secondary_link'],
        true,
        false,
      ],
      ['has', 'name_ref'],
    ],
  },
]
