// Autogenerated by `scripts/MapboxStyles/process.ts`
// Do not change this file manually

import { MapboxStyleLayer } from '../types'

export const mapboxStyleGroupLayers_parking_debug_parking_points: MapboxStyleLayer[] = [
  {
    type: 'fill',
    id: 'parking-point-area',
    paint: {
      'fill-color': 'rgba(80, 139, 134, 0.7)',
    },
  },
  {
    minzoom: 16.5,
    type: 'line',
    id: 'parking-point-border',
    paint: {
      'line-dasharray': [2, 2],
      'line-color': 'rgb(0, 0, 0)',
    },
  },
]
