// DO NOT EDIT MANUALLY
// This file was automatically generated by `saveConfigs.ts`

import { MapDataCategoryParam } from '../../type'

// For regions radinfra
export const _1ops5da: MapDataCategoryParam[] = [
  {
    id: 'radinfra_bikelanes',
    active: false,
    subcategories: [
      {
        id: 'bikelanes',
        styles: [
          { id: 'hidden', active: false },
          { id: 'default', active: true },
          { id: 'details', active: false },
        ],
      },
      { id: 'bikelanes_plus_routes', styles: [{ id: 'default', active: false }] },
    ],
  },
  {
    id: 'radinfra_surface',
    active: false,
    subcategories: [
      { id: 'bikelanes', styles: [{ id: 'default', active: true }] },
      { id: 'bikelanes_plus_surface_smoothness', styles: [{ id: 'default', active: false }] },
    ],
  },
  {
    id: 'radinfra_width',
    active: false,
    subcategories: [
      { id: 'bikelanes', styles: [{ id: 'default', active: true }] },
      { id: 'bikelanes_plus_width', styles: [{ id: 'default', active: false }] },
    ],
  },
  {
    id: 'radinfra_oneway',
    active: false,
    subcategories: [{ id: 'bikelanes', styles: [{ id: 'default', active: true }] }],
  },
  {
    id: 'radinfra_trafficSigns',
    active: false,
    subcategories: [{ id: 'bikelanes', styles: [{ id: 'default', active: true }] }],
  },
  {
    id: 'radinfra_currentness',
    active: false,
    subcategories: [{ id: 'bikelanes', styles: [{ id: 'default', active: true }] }],
  },
  {
    id: 'radinfra_campagins',
    active: false,
    subcategories: [
      {
        id: 'campaigns',
        styles: [
          { id: 'default', active: true },
          { id: 'adjoining_or_isolated', active: false },
          { id: 'advisory_or_exclusive', active: false },
          { id: 'missing_access_tag_240', active: false },
          { id: 'missing_access_tag_bicycle_road', active: false },
          { id: 'missing_oneway', active: false },
          { id: 'missing_segregated', active: false },
          { id: 'mixed_cycleway_both', active: false },
          { id: 'needs_clarification', active: false },
          { id: 'needs_clarification_track', active: false },
          { id: 'unexpected_bicycle_access_on_footway', active: false },
          { id: 'currentness_too_old', active: false },
          { id: 'malformed_traffic_sign', active: false },
          { id: 'missing_surface', active: false },
          { id: 'missing_traffic_sign', active: false },
          { id: 'missing_traffic_sign_244', active: false },
          { id: 'missing_traffic_sign_vehicle_destination', active: false },
          { id: 'missing_width', active: false },
          { id: 'deprecated_cycleway_shared', active: false },
        ],
      },
    ],
  },
  {
    id: 'radinfra_mapillary',
    active: false,
    subcategories: [
      {
        id: 'mapillaryCoverage',
        styles: [
          { id: 'hidden', active: false },
          { id: 'default', active: true },
          { id: 'all', active: false },
          { id: 'age', active: false },
          { id: 'pano', active: false },
        ],
      },
      { id: 'mapillaryPlus', styles: [{ id: 'default', active: true }] },
    ],
  },
]
