// DO NOT EDIT MANUALLY
// this file was automatically generated by `saveConfigs.ts`

import { MapDataCategoryParam } from '../../type'

export const _tztqka: MapDataCategoryParam[] = [
  {
    id: 'parking',
    active: false,
    subcategories: [
      {
        id: 'parking',
        styles: [
          { id: 'hidden', active: false },
          { id: 'default', active: true },
          { id: 'presence', active: false },
          { id: 'surface', active: false },
        ],
      },
      {
        id: 'parkingPoints',
        styles: [
          { id: 'hidden', active: true },
          { id: 'default', active: false },
        ],
      },
      {
        id: 'parkingAreas',
        styles: [
          { id: 'hidden', active: false },
          { id: 'default', active: true },
          { id: 'street_side', active: false },
        ],
      },
      {
        id: 'parkingDebug',
        styles: [
          { id: 'hidden', active: true },
          { id: 'default', active: false },
        ],
      },
      {
        id: 'parkingStats',
        styles: [
          { id: 'hidden', active: true },
          { id: 'stats-admin-level-4', active: false },
          { id: 'default', active: false },
          { id: 'stats-admin-level-10', active: false },
          { id: 'length-admin-level-4', active: false },
          { id: 'length-admin-level-9', active: false },
          { id: 'length-admin-level-10', active: false },
        ],
      },
      {
        id: 'signs',
        styles: [
          { id: 'hidden', active: true },
          { id: 'default', active: false },
        ],
      },
    ],
  },
  {
    id: 'poi',
    active: false,
    subcategories: [
      {
        id: 'poi',
        styles: [
          { id: 'hidden', active: false },
          { id: 'default', active: true },
          { id: 'education', active: false },
        ],
      },
      {
        id: 'poiPlaces',
        styles: [
          { id: 'hidden', active: false },
          { id: 'default', active: true },
          { id: 'circle', active: false },
        ],
      },
      {
        id: 'poiBoundaries',
        styles: [
          { id: 'hidden', active: true },
          { id: 'default', active: false },
          { id: 'category_district_label', active: false },
          { id: 'category_municipality', active: false },
          { id: 'category_municipality_label', active: false },
        ],
      },
      { id: 'poiPlusBarriers', styles: [{ id: 'default', active: false }] },
      { id: 'poiPlusLanduse', styles: [{ id: 'default', active: false }] },
      { id: 'poiPlusPublicTransport', styles: [{ id: 'default', active: false }] },
    ],
  },
  {
    id: 'trafficSigns',
    active: false,
    subcategories: [
      {
        id: 'signs',
        styles: [
          { id: 'hidden', active: true },
          { id: 'default', active: false },
        ],
      },
    ],
  },
  {
    id: 'mapillary',
    active: false,
    subcategories: [
      {
        id: 'mapillaryCoverage',
        styles: [
          { id: 'hidden', active: false },
          { id: 'default', active: true },
          { id: 'all', active: false },
          { id: 'age', active: false },
          { id: 'pano', active: false },
        ],
      },
    ],
  },
]
