// DO NOT EDIT MANUALLY
// This file was automatically generated by `saveConfigs.ts`

import { _17dmq3y } from './_17dmq3y'
import { _19sklui } from './_19sklui'
import { _1cjo3ur } from './_1cjo3ur'
import { _1d3t4i0 } from './_1d3t4i0'
import { _1dhu3si } from './_1dhu3si'
import { _1e6163i } from './_1e6163i'
import { _1gk36d0 } from './_1gk36d0'
import { _1j7ax4m } from './_1j7ax4m'
import { _1k7izoy } from './_1k7izoy'
import { _1lhd7a } from './_1lhd7a'
import { _1ljsnj0 } from './_1ljsnj0'
import { _1oy2q4i } from './_1oy2q4i'
import { _1p0kkkw } from './_1p0kkkw'
import { _1r88sri } from './_1r88sri'
import { _1tdocms } from './_1tdocms'
import { _1x5utcr } from './_1x5utcr'
import { _1ybiojr } from './_1ybiojr'
import { _b5k2yc } from './_b5k2yc'
import { _c8lcr0 } from './_c8lcr0'
import { _eu560i } from './_eu560i'
import { _gdl8v6 } from './_gdl8v6'
import { _nq3m12 } from './_nq3m12'
import { _qver32 } from './_qver32'
import { _rcqwse } from './_rcqwse'
import { _tztqka } from './_tztqka'
import { _up0vgv } from './_up0vgv'
import { _vvhkik } from './_vvhkik'
import { _wvqr4 } from './_wvqr4'
import { _yx2kv4 } from './_yx2kv4'
import { bbbeteiligung_z9tzbb } from './bbbeteiligung_z9tzbb'
import { bbkampagne_bv3m8i } from './bbkampagne_bv3m8i'
import { bbsg_166cmie } from './bbsg_166cmie'
import { berlin_1swjsz2 } from './berlin_1swjsz2'
import { bibi_l464fe } from './bibi_l464fe'
import { deutschland_r6m1yq } from './deutschland_r6m1yq'
import { fahrradstellplaetze_diykzs } from './fahrradstellplaetze_diykzs'
import { magdeburg_14zbfci } from './magdeburg_14zbfci'
import { muenchen_1qeycq8 } from './muenchen_1qeycq8'
import { nudafa_e6ilf4 } from './nudafa_e6ilf4'
import { pankow_iv8u2n } from './pankow_iv8u2n'
import { parkraum_1r6doko } from './parkraum_1r6doko'
import { parkraumberlineuvm_1874z8l } from './parkraumberlineuvm_1874z8l'
import { radinfra_ife2uk } from './radinfra_ife2uk'
import { radplus_st5qyw } from './radplus_st5qyw'
import { testing_1rg9mwb } from './testing_1rg9mwb'

export const configs = {
  '17dmq3y': _17dmq3y,
  '19sklui': _19sklui,
  '1cjo3ur': _1cjo3ur,
  '1d3t4i0': _1d3t4i0,
  '1dhu3si': _1dhu3si,
  '1e6163i': _1e6163i,
  '1gk36d0': _1gk36d0,
  '1j7ax4m': _1j7ax4m,
  '1k7izoy': _1k7izoy,
  '1lhd7a': _1lhd7a,
  '1ljsnj0': _1ljsnj0,
  '1oy2q4i': _1oy2q4i,
  '1p0kkkw': _1p0kkkw,
  '1r88sri': _1r88sri,
  '1tdocms': _1tdocms,
  '1x5utcr': _1x5utcr,
  '1ybiojr': _1ybiojr,
  b5k2yc: _b5k2yc,
  c8lcr0: _c8lcr0,
  eu560i: _eu560i,
  gdl8v6: _gdl8v6,
  nq3m12: _nq3m12,
  qver32: _qver32,
  rcqwse: _rcqwse,
  tztqka: _tztqka,
  up0vgv: _up0vgv,
  vvhkik: _vvhkik,
  wvqr4: _wvqr4,
  yx2kv4: _yx2kv4,
  z9tzbb: bbbeteiligung_z9tzbb,
  bv3m8i: bbkampagne_bv3m8i,
  '166cmie': bbsg_166cmie,
  '1swjsz2': berlin_1swjsz2,
  l464fe: bibi_l464fe,
  r6m1yq: deutschland_r6m1yq,
  diykzs: fahrradstellplaetze_diykzs,
  '14zbfci': magdeburg_14zbfci,
  '1qeycq8': muenchen_1qeycq8,
  e6ilf4: nudafa_e6ilf4,
  iv8u2n: pankow_iv8u2n,
  '1r6doko': parkraum_1r6doko,
  '1874z8l': parkraumberlineuvm_1874z8l,
  ife2uk: radinfra_ife2uk,
  st5qyw: radplus_st5qyw,
  '1rg9mwb': testing_1rg9mwb,
}
