// DO NOT EDIT MANUALLY
// This file was automatically generated by `saveConfigs.ts`

import { MapDataCategoryParam } from '../../type'

// For region pankow (Pankow)
export const pankow_iv8u2n: MapDataCategoryParam[] = [
  {
    id: 'mapillary',
    active: false,
    subcategories: [
      {
        id: 'mapillaryCoverage',
        styles: [
          { id: 'hidden', active: false },
          { id: 'default', active: true },
          { id: 'all', active: false },
          { id: 'age', active: false },
          { id: 'pano', active: false },
        ],
      },
    ],
  },
]
