#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# This is `npm run check`
# TODO: Disabled until we finished migrating the atlas 0.1 code to blitzjs

# npm run type-check
# npm run lint
# npm run format
# npm run test:run
