import { $ } from 'bun'
import path from 'node:path'
import { radinfraDeCampaignSchema } from '../../src/app/regionen/(index)/_data/radinfraDeCampaignSchema'
import { greenCheckmark } from '../../src/instrumentation/_utils/greenCheckmark'

const url = 'https://radinfra.de/api/campaigns.json'

export const main = async () => {
  try {
    const response = await fetch(url)
    if (!response.ok) {
      throw new Error(`HTTP error! Status: ${response.status}`)
    }
    const json = await response.json()
    const parsed = radinfraDeCampaignSchema.parse(json)
    const sorted = parsed.sort((c1, c2) => c1.id.localeCompare(c2.id))

    const data = `
// DO NOT EDIT MANUALLY
// This file was automatically generated by \`app/scripts/RadinfraDeCampaigns/updateCache.ts\`
// To update, restart the dev server or run \`npm run predev:update_campaigns\`

import { RadinfraDeCampaignSchema } from './radinfraDeCampaignSchema'

export const radinfraDeCampaigns: RadinfraDeCampaignSchema[] = ${JSON.stringify(sorted, undefined, 2)}
`

    const filePath = path.resolve(
      __dirname,
      '../../src/app/regionen/(index)/_data/radinfraDeCampaigns.generated.const.ts',
    )
    await Bun.write(filePath, data.trim())

    // On Dev, where we check the file in, we make sure it is formatted nicely.
    await $`npx prettier --write "${filePath}"`

    console.log(greenCheckmark, 'radinfra.de Campaign data updated')
  } catch (error) {
    console.error(
      '\x1b[31m%s\x1b[0m',
      'INSTRUMENTATION HOOK FAILED',
      'cacheRadinfraDeCampaigns',
      error,
    )
  }
}

main()
