# this file is copied to the staging or production server to be used there

services:
  app:
    env_file:
      - ./.env
    image: public.ecr.aws/n0p8j4k5/atlas/blitz:${GITHUB_SHA}
    container_name: blitz
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}/${DATABASE_NAME}?schema=prisma
      NEXT_TELEMETRY_DISABLED: 1
      NEXT_PUBLIC_APP_ENV:
      SESSIONS_SECRET_KEY:
    ports:
      - 4000:4000
    labels:
      traefik.enable: true
      traefik.http.services.container.loadbalancer.server.port: 4000
      traefik.http.routers.container.rule: Host(`${APP_URL}`) || Host(`www.${APP_URL}`)
      traefik.http.routers.container.entrypoints: websecure
      traefik.http.routers.container.tls.certresolver: letsencrypt
      traefik.http.routers.container.tls: true
    networks:
      - processing_app_bridge
    logging:
      driver: journald

networks:
  processing_app_bridge:
    external: true
