name: Check PR

on: [pull_request]

jobs:
  run-app-ci:
    name: Run Type Check & Linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: 'app/.nvmrc'

      - name: Install dependencies (with cache)
        uses: bahmutov/npm-install@HEAD

      - name: Check types
        run: npm run type-check

      - name: Check linting
        run: npm run lint

      - name: Run tests
        run: npm run test:run
  run-processing-ci:
    name: Run Processing Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./processing.Dockerfile
          tags: test_img
          target: testing
          push: false
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run Tests
        run: |
          docker run test_img
