name: Deploy Processing to Ionos

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        type: string
        required: true
      TILES_URL:
        type: string
        required: true

jobs:
  check_changes_processing:
    uses: ./.github/workflows/diff-last-run.yml
    with:
      CHECK_DIFF_LOCATIONS: processing/ warm-cache/ processing.Dockerfile
  build_and_deploy_processing:
    needs: check_changes_processing
    if: ${{ needs.check_changes_processing.outputs.changes == 'true' }}
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.ENVIRONMENT }}
      url: https://${{ inputs.TILES_URL }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Upgrade AWS CLI version and setup lightsailctl
        run: |
          aws --version
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --bin-dir /usr/local/bin --install-dir /usr/local/aws-cli --update
          which aws
          aws --version
          sudo curl "https://s3.us-west-2.amazonaws.com/lightsailctl/latest/linux-amd64/lightsailctl" -o "/usr/local/bin/lightsailctl"
          sudo chmod +x /usr/local/bin/lightsailctl

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup buildx
        uses: docker/setup-buildx-action@v3

      - name: Build app image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./processing.Dockerfile
          push: false
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            public.ecr.aws/n0p8j4k5/atlas/app:${{ github.sha }}
            public.ecr.aws/n0p8j4k5/atlas/app:${{ inputs.ENVIRONMENT }}-latest

      - name: Push the app image
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/n0p8j4k5/
          docker push --all-tags public.ecr.aws/n0p8j4k5/atlas/app

      - name: Stop & Start containers on VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /srv
            echo "Pulling latest image"
            docker compose pull processing
            echo "Restarting processing container"
            docker compose -f docker-compose.yml -f docker-compose.network.yml up processing -d
            echo "Pruning images"
            docker image prune -fa
