name: Deploy Staging
on:
  push:
    branches:
      - develop
      - tinkering
jobs:
  setup_env:
    uses: ./.github/workflows/setup-env.yml
    with:
      ENVIRONMENT: staging
      TILES_URL: staging-tiles.tilda-geo.de
      CACHELESS_URL: staging-cacheless.tilda-geo.de
      NEXT_PUBLIC_APP_ORIGIN: https://staging.tilda-geo.de
      NEXT_PUBLIC_APP_ENV: staging
      NEXT_PUBLIC_OSM_API_URL: https://master.apis.dev.openstreetmap.org/api/0.6
      APP_URL: staging.tilda-geo.de
    secrets: inherit
  restart_services:
    uses: ./.github/workflows/restart-services.yml
    needs: setup_env
    with:
      ENVIRONMENT: staging
    secrets: inherit
  deploy_processing:
    uses: ./.github/workflows/deploy-processing.yml
    needs: restart_services
    with:
      ENVIRONMENT: staging
      TILES_URL: staging-tiles.tilda-geo.de
      CONFIG_CHANGED: ${{ needs.restart_services.outputs.CHANGES == 'true' }}
    secrets: inherit
  deploy_app:
    uses: ./.github/workflows/deploy-app.yml
    needs: restart_services
    with:
      ENVIRONMENT: staging
      NEXT_PUBLIC_APP_ORIGIN: https://staging.tilda-geo.de
      NEXT_PUBLIC_APP_ENV: staging
      NEXT_PUBLIC_OSM_API_URL: https://master.apis.dev.openstreetmap.org/api/0.6
      APP_URL: staging.tilda-geo.de
      CONFIG_CHANGED: ${{ needs.restart_services.outputs.CHANGES == 'true' }}
    secrets: inherit
