name: Deploy Production
on:
  push:
    branches:
      - main
jobs:
  call-deploy-app:
    uses: ./.github/workflows/deploy-app.yml
    with:
      ENVIRONMENT: production
      NEXT_PUBLIC_APP_ORIGIN: https://radverkehrsatlas.de
      NEXT_PUBLIC_APP_ENV: production
      TRAEFIK_HOST: radverkehrsatlas.de
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      SESSION_SECRET_KEY: ${{ secrets.SESSION_SECRET_KEY }}
      OSM_CLIENT_ID: ${{ secrets.OSM_CLIENT_ID }}
      OSM_CLIENT_SECRET: ${{ secrets.OSM_CLIENT_SECRET }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      ATLAS_API_KEY: ${{ secrets.ATLAS_API_KEY }}
      S3_PMTILES_KEY: ${{ secrets.S3_PMTILES_KEY }}
      S3_PMTILES_SECRET: ${{ secrets.S3_PMTILES_SECRET }}
      S3_PMTILES_REGION: ${{ secrets.S3_PMTILES_REGION }}
