name: Deploy Staging
on:
  push:
    branches:
      - develop
      - tinkering
jobs:
  call-deploy-app:
    uses: ./.github/workflows/deploy-app.yml
    with:
      ENVIRONMENT: staging
      NEXT_PUBLIC_APP_ORIGIN: https://staging.radverkehrsatlas.de
      NEXT_PUBLIC_APP_ENV: staging
      NEXT_PUBLIC_OSM_API_URL: https://master.apis.dev.openstreetmap.org/api/0.6
      TRAEFIK_HOST: staging.radverkehrsatlas.de
    secrets:
      # REMINDER: Public keys `NEXT_PUBLIC_*` have to be added to `/Dockerfile` as well
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      SESSION_SECRET_KEY: ${{ secrets.SESSION_SECRET_KEY }}
      OSM_CLIENT_ID: ${{ secrets.OSM_CLIENT_ID }}
      OSM_CLIENT_SECRET: ${{ secrets.OSM_CLIENT_SECRET }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      ATLAS_API_KEY: ${{ secrets.ATLAS_API_KEY }}
      S3_KEY: ${{ secrets.S3_KEY }}
      S3_SECRET: ${{ secrets.S3_SECRET }}
      S3_REGION: ${{ secrets.S3_REGION }}
      S3_BUCKET: ${{ secrets.S3_BUCKET }}
