name: Deploy Staging
on:
  push:
    branches:
      - develop
jobs:
  call-deploy-app:
    uses: ./.github/workflows/deploy-app.yml
    with:
      ENVIRONMENT: staging
      NEXT_PUBLIC_APP_ORIGIN: https://staging.radverkehrsatlas.de
      NEXT_PUBLIC_ENV: staging
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      SESSION_SECRET_KEY: ${{ secrets.SESSION_SECRET_KEY }}
      OSM_CLIENT_ID: ${{ secrets.OSM_CLIENT_ID }}
      OSM_CLIENT_SECRET: ${{ secrets.OSM_CLIENT_SECRET }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
