name: Deploy Production
on:
  push:
    branches:
      - main
jobs:
  setup_env:
    uses: ./.github/workflows/setup-env.yml
    with:
      ENVIRONMENT: production
      TILES_URL: tiles.radverkehrsatlas.de
      CACHELESS_URL: cacheless.radverkehrsatlas.de
      NEXT_PUBLIC_APP_ORIGIN: https://radverkehrsatlas.de
      NEXT_PUBLIC_APP_ENV: production
      NEXT_PUBLIC_OSM_API_URL: https://api.openstreetmap.org/api/0.6
      APP_URL: radverkehrsatlas.de
    secrets: inherit
  restart_services:
    uses: ./github/workflows/restart-services.yml
    needs: setup_env
    with:
      ENVIRONMENT: production
    secrets: inherit
  deploy_processing:
    needs: restart_services
    uses: ./.github/workflows/deploy-processing.yml
    with:
      ENVIRONMENT: production
      TILES_URL: tiles.radverkehrsatlas.de
    secrets: inherit
  deploy_app:
    uses: ./.github/workflows/deploy-app.yml
    needs: restart_services
    with:
      ENVIRONMENT: production
      NEXT_PUBLIC_APP_ORIGIN: https://radverkehrsatlas.de
      NEXT_PUBLIC_APP_ENV: production
      NEXT_PUBLIC_OSM_API_URL: https://api.openstreetmap.org/api/0.6
      APP_URL: radverkehrsatlas.de
    secrets: inherit
