name: Regenerate Campaign Tasks

on:
  workflow_dispatch:
  schedule:
    # Runs every Friday at 9:00 AM
    - cron: '0 9 * * 5'
jobs:
  generate-maproulette-tasks:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Trigger MapRoulette Campaign Task regeneration
        run: curl --fail -s -S -X GET "https://tilda-geo.de/api/private/generate-maproulette-tasks?apiKey=${{ secrets.ATLAS_API_KEY }}"
