name: Regenerate Staging Tiles

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * 1"
jobs:
  generate-tiles:
    uses: ./.github/workflows/generate-tiles.yml
    with:
      ENVIRONMENT: staging
      url: https://staging-tiles.tilda-geo.de
    secrets:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
