name: Regenerate Tiles

on:
  workflow_call:
    secrets:
      SSH_USERNAME:
        required: true
      SSH_PASSWORD:
        required: true
      SSH_HOST:
        required: true
    inputs:
      ENVIRONMENT:
        type: string
        required: true
      url:
        type: string
        required: true
jobs:
  generate-tiles:
    environment:
      name: ${{inputs.ENVIRONMENT}}
      url: ${{inputs.url}}
    runs-on: ubuntu-latest

    steps:
      - name: Start tile generation
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            echo "Restarting `processing` container"
            cd /srv/
            export WAIT_FOR_FRESH_DATA=1
            export SKIP_DOWNLOAD=0
            export COMPUTE_DIFFS=0
            docker compose down processing
            docker compose up -d processing
            unset WAIT_FOR_FRESH_DATA
            unset SKIP_DOWNLOAD
            unset COMPUTE_DIFFS
