name: Check PR
on: [pull_request]
jobs:
  run-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build Image
        run: |
          docker compose build processing
      - name: Run Tests
        run: |
          ./run-tests.sh
