name: Check PR
on: [pull_request]
jobs:
  run-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build Image
        run: |
          docker build --target lua -f processing.Dockerfile -t test_img .
      - name: Run Tests
        run: |
          docker run -v ./processing:/processing test_img busted /processing/topics/ -p %.test%.lua$
