name: Deployment Staging

on:
  push:
    branches:
      - "develop"

jobs:
  build_and_deploy:
    uses: ./.github/workflows/deployment.yml
    with:
      DATABASE_PORT: ${{ vars.DATABASE_PORT }}
      DATABASE_HOST: ${{ vars.DATABASE_HOST }}
      ENVIRONMENT: staging
      URL: staging-tiles.radverkehrsatlas.de
    secrets:
      SERVICE_NAME: ${{ secrets.SERVICE_NAME }}
      DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
      DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      DATABASE_USER: ${{ secrets.DATABASE_USER }}
      DATABASE_PASSWORD_ENCODED: ${{ secrets.DATABASE_PASSWORD_ENCODED }}

